// @vitest-environment jsdom

import { fireEvent, render, screen } from '@testing-library/react';
import { beforeEach, describe, expect, test, vi } from 'vitest';

const generateMutate = vi.fn();
const dismissMutate = vi.fn();
const deleteMutate = vi.fn();
const logChat = vi.fn();

// The card observes generation runs via `useMutationState` (shared mutation
// key, archive#3310); tests drive that observation directly.
let mutationStates: Array<{
  status: 'pending' | 'error' | 'success' | 'idle';
  conversationId?: string;
  errorMessage?: string;
  submittedAt: number;
}> = [];
let queryResult: { data: unknown; isLoading: boolean; error: Error | null };

vi.mock('@tanstack/react-query', () => ({
  useMutationState: () => mutationStates,
}));

vi.mock('@kontourai/station-sdk', () => ({
  SESSION_SUMMARY_GENERATE_MUTATION_KEY: ['session-summary-generate'],
  useSessionSummaryQuery: () => queryResult,
  useGenerateSessionSummaryMutation: () => ({
    mutate: generateMutate,
    isPending: false,
    error: null,
  }),
  useDismissSessionSummaryMutation: () => ({
    mutate: dismissMutate,
    isPending: false,
    error: null,
  }),
  useDeleteSessionSummaryMutation: () => ({
    mutate: deleteMutate,
    isPending: false,
    error: null,
  }),
}));

vi.mock('../utils/logger', () => ({
  log: { chat: (...args: unknown[]) => logChat(...args) },
}));

import { SessionSummaryCard } from '../components/chat/SessionSummaryCard';

const SUMMARY = {
  text: 'The bounded path was selected.',
  model: 'structure-model',
  generatedAt: '2026-08-16T12:00:00.000Z',
  summarizedFromMessageId: 'm1',
  summarizedThroughMessageId: 'm2',
  summarizedMessageCount: 2,
  sourceMessageCount: 5,
  partialMessageIncluded: true,
  stale: true,
};

// The dock host claims its own entry point (the header gear opens
// ChatSettingsPanel), which is what licenses the archive#3310 demotion. A host that
// does NOT claim one is covered separately below.
function renderCard(
  opts: { hasSettingsEntryPoint?: boolean; conversationId?: string } = {},
) {
  return render(
    <SessionSummaryCard
      activeSession={
        {
          agentSlug: 'station',
          conversationId: opts.conversationId ?? 'c1',
        } as any
      }
      hasSettingsEntryPoint={opts.hasSettingsEntryPoint ?? true}
    />,
  );
}

beforeEach(() => {
  generateMutate.mockClear();
  dismissMutate.mockClear();
  deleteMutate.mockClear();
  logChat.mockClear();
  mutationStates = [];
  queryResult = { data: null, isLoading: false, error: null };
});

describe('SessionSummaryCard', () => {
  test('renders model-attributed derived output as a complementary region, never a transcript message', () => {
    queryResult = { data: SUMMARY, isLoading: false, error: null };
    renderCard();
    const summary = screen.getByRole('complementary', {
      name: 'Derived session summary',
    });
    expect(summary.textContent).toContain('Session summary');
    expect(summary.textContent).toContain('Derived');
    expect(summary.textContent).toContain('Generated by structure-model');
    expect(summary.textContent).toContain('Stale — newer turns exist');
    expect(summary.textContent).toContain('Latest 2 of 5 messages summarized');
    expect(summary.textContent).toContain('final message partially included');
    expect(summary.closest('[role="log"]')).toBeNull();
    fireEvent.click(screen.getByRole('button', { name: 'Regenerate' }));
    fireEvent.click(screen.getByRole('button', { name: 'Dismiss summary' }));
    expect(generateMutate).toHaveBeenCalledWith({
      agentSlug: 'station',
      conversationId: 'c1',
    });
    expect(dismissMutate).toHaveBeenCalledWith({
      agentSlug: 'station',
      conversationId: 'c1',
    });
  });

  test('links production related Task evidence without promoting it to verification', () => {
    queryResult = {
      data: {
        ...SUMMARY,
        version: 2,
        overview: SUMMARY.text,
        goals: [],
        constraints: [],
        progress: [],
        nextSteps: [],
        reportedCompletion: [],
        sourceRange: {
          fromMessageId: 'm1',
          throughMessageId: 'm2',
          messageCount: 2,
        },
        sourceRanges: [
          { fromMessageId: 'm1', throughMessageId: 'm2', messageCount: 2 },
        ],
        sourceRevision: 'revision',
        contextBoundaryCount: 0,
        contextBoundaries: [],
        generationUsage: { state: 'unknown' },
        relatedEvidenceRefs: [
          {
            kind: 'task-turn',
            taskId: 'task-1',
            turnId: 'turn-1',
            eventId: 'event-1',
          },
        ],
        verificationRefs: [
          {
            kind: 'task-turn',
            state: 'unavailable',
            unavailableReason: 'not-captured-by-station',
          },
        ],
      },
      isLoading: false,
      error: null,
    };
    renderCard();
    expect(
      screen.getByRole('link', { name: 'Task reference' }).getAttribute('href'),
    ).toBe('/tasks/task-1');
    expect(
      screen.getByText(
        'Related Task/turn evidence — does not verify completion',
      ),
    ).toBeTruthy();
    expect(
      screen.getByText(/Independent verification: unavailable/),
    ).toBeTruthy();
    expect(
      screen.queryByText('Independent verification', { selector: 'strong' }),
    ).toBeNull();
    expect(
      screen
        .getByRole('link', { name: 'Messages m1 through m2' })
        .getAttribute('href'),
    ).toBe('#station-message=m1');
  });

  test.each([
    [
      'empty-next-cold-start',
      'Prior transcript not injected. Summary separately reads canonical history.',
    ],
    ['continue-from-history', 'Prior transcript re-anchored and injected.'],
  ] as const)(
    'copies %s context-boundary facts exactly',
    (policy, disclosure) => {
      queryResult = {
        data: {
          ...SUMMARY,
          version: 2,
          overview: SUMMARY.text,
          goals: [],
          constraints: [],
          progress: [],
          nextSteps: [],
          reportedCompletion: [],
          sourceRange: {
            fromMessageId: 'm1',
            throughMessageId: 'm2',
            messageCount: 2,
          },
          sourceRanges: [
            { fromMessageId: 'm1', throughMessageId: 'm2', messageCount: 2 },
          ],
          sourceRevision: 'revision',
          contextBoundaryCount: 1,
          contextBoundaries: [
            {
              boundaryId: 'boundary',
              policy,
              priorTranscriptInjected: policy === 'continue-from-history',
            },
          ],
          generationUsage: { state: 'unknown' },
          relatedEvidenceRefs: [],
          verificationRefs: [
            {
              kind: 'task-turn',
              state: 'unavailable',
              unavailableReason: 'not-captured-by-station',
            },
          ],
        },
        isLoading: false,
        error: null,
      };
      renderCard();
      expect(screen.getByText(disclosure)).toBeTruthy();
    },
  );

  // archive#3310: the un-generated state pays zero transcript pixels — the entry
  // point lives in the chat-settings menu, not in a permanent band.
  test('renders nothing when no summary exists and nothing is in flight', () => {
    const { container } = renderCard();
    expect(container.innerHTML).toBe('');
    expect(
      screen.queryByRole('button', { name: 'Summarize session' }),
    ).toBeNull();
  });

  // archive#3310: a failed summary QUERY is nothing the user did — degrade silently
  // (logged), never an alert band inside the chat.
  test('a failed summary query renders nothing and logs instead of alerting', () => {
    queryResult = {
      data: null,
      isLoading: false,
      error: new Error('summary backend down'),
    };
    const { container } = renderCard();
    expect(container.innerHTML).toBe('');
    expect(screen.queryByRole('alert')).toBeNull();
    expect(logChat).toHaveBeenCalled();
  });

  test('shows an in-flight state while a generation for THIS conversation runs', () => {
    mutationStates = [
      { status: 'pending', conversationId: 'c1', submittedAt: 1 },
    ];
    renderCard();
    expect(screen.getByRole('status').textContent).toBe('Generating summary…');
  });

  test('a generation for a different conversation renders nothing here', () => {
    mutationStates = [
      { status: 'pending', conversationId: 'other', submittedAt: 1 },
    ];
    const { container } = renderCard();
    expect(container.innerHTML).toBe('');
  });

  test('failed generation offers Retry and a dismiss that clears the notice', () => {
    mutationStates = [
      {
        status: 'error',
        conversationId: 'c1',
        errorMessage: 'model unavailable',
        submittedAt: 5,
      },
    ];
    const { container } = renderCard();

    const alert = screen.getByRole('alert');
    expect(alert.textContent).toContain('Summary generation failed');
    expect(alert.textContent).toContain('model unavailable');

    fireEvent.click(screen.getByRole('button', { name: 'Retry' }));
    expect(generateMutate).toHaveBeenCalledWith({
      agentSlug: 'station',
      conversationId: 'c1',
    });

    fireEvent.click(screen.getByRole('button', { name: 'Dismiss' }));
    expect(screen.queryByRole('alert')).toBeNull();
    expect(container.innerHTML).toBe('');
  });
});

/**
 * archive#3310 (MERGE-BLOCKER): `ChatMessageList` has a
 * second host — `ACPChatPanel` — which renders no gear and no
 * `ChatSettingsPanel`. Demoting the inline button unconditionally removed the
 * ONLY way to summarize an ACP chat, while the component's own docblock went
 * on asserting the entry point "lives in the chat-settings menu". The default
 * is therefore false: a host keeps the button until it claims an entry point.
 */
describe('SessionSummaryCard entry-point reachability', () => {
  test('a host with no settings entry point keeps the inline Summarize button', () => {
    renderCard({ hasSettingsEntryPoint: false });
    const button = screen.getByRole('button', { name: 'Summarize session' });
    fireEvent.click(button);
    expect(generateMutate).toHaveBeenCalledWith({
      agentSlug: 'station',
      conversationId: 'c1',
    });
  });

  test('the button is the DEFAULT — a host must opt in to lose it', () => {
    render(
      <SessionSummaryCard
        activeSession={{ agentSlug: 'station', conversationId: 'c1' } as any}
      />,
    );
    expect(
      screen.getByRole('button', { name: 'Summarize session' }),
    ).toBeTruthy();
  });

  test('a host without an entry point still shows a real summary, not the button', () => {
    queryResult = { data: SUMMARY, isLoading: false, error: null };
    renderCard({ hasSettingsEntryPoint: false });
    expect(
      screen.queryByRole('button', { name: 'Summarize session' }),
    ).toBeNull();
    expect(screen.getByRole('button', { name: 'Regenerate' })).toBeTruthy();
  });
});

/**
 * archive#3310: the card mounts ONCE per host and is
 * never re-keyed when the active chat changes, while `submittedAt` is
 * wall-clock. A single dismissal scalar therefore let a dismissal in one
 * conversation hide an OLDER, never-seen failure in another — that chat
 * rendered nothing at all, with no Retry and no notice it had failed.
 */
describe('SessionSummaryCard failure dismissal is per conversation', () => {
  test('dismissing one conversation does not hide an older failure in another', () => {
    mutationStates = [
      {
        status: 'error',
        conversationId: 'c1',
        errorMessage: 'late failure',
        submittedAt: 10_005,
      },
    ];
    // ONE mounted card, re-rendered with a different conversation — the app
    // never re-keys or remounts it, and that is the whole defect. An earlier
    // version of this test unmounted and re-rendered instead, which reset the
    // component's state and made it pass against the global-scalar bug.
    const view = renderCard({ conversationId: 'c1' });
    fireEvent.click(screen.getByRole('button', { name: 'Dismiss' }));
    expect(screen.queryByRole('alert')).toBeNull();

    // The OTHER conversation's failure is OLDER than the dismissal above.
    mutationStates = [
      {
        status: 'error',
        conversationId: 'c2',
        errorMessage: 'earlier failure',
        submittedAt: 10_000,
      },
    ];
    view.rerender(
      <SessionSummaryCard
        activeSession={{ agentSlug: 'station', conversationId: 'c2' } as any}
        hasSettingsEntryPoint
      />,
    );
    expect(screen.getByRole('alert').textContent).toContain('earlier failure');
    expect(screen.getByRole('button', { name: 'Retry' })).toBeTruthy();
  });

  test('a NEW failure after a dismissal shows again in the same conversation', () => {
    mutationStates = [
      {
        status: 'error',
        conversationId: 'c1',
        errorMessage: 'first failure',
        submittedAt: 5,
      },
    ];
    const view = renderCard();
    fireEvent.click(screen.getByRole('button', { name: 'Dismiss' }));
    expect(screen.queryByRole('alert')).toBeNull();

    // A later run for the SAME conversation must resurface (submittedAt moved
    // forward) — the claim the component's own comment makes.
    mutationStates = [
      {
        status: 'error',
        conversationId: 'c1',
        errorMessage: 'second failure',
        submittedAt: 6,
      },
    ];
    view.rerender(
      <SessionSummaryCard
        activeSession={{ agentSlug: 'station', conversationId: 'c1' } as any}
        hasSettingsEntryPoint
      />,
    );
    expect(screen.getByRole('alert').textContent).toContain('second failure');
  });
});
