/**
 * Opt-in Workspace Pane contract surface. Import this subpath when adapting
 * baseline layouts or reading a Pane catalog; the SDK root intentionally keeps
 * these runtime helpers out of ordinary React bundles.
 */

export type {
  EnumerableLayoutDefinition,
  LayoutCatalogContribution,
  MCPAppDisplayMode,
  MCPAppDisplayModeDecision,
  MCPAppDisplayModeDeclineReason,
  MCPAppDisplayModeIntent,
  MCPAppPanePresentation,
  MCPAppPanePresentationIdentity,
  WorkspaceCompositionCapabilityRequirement,
  WorkspaceCompositionCapabilityState,
  WorkspaceCompositionInstantiationFailure,
  WorkspaceCompositionInstantiationResult,
  WorkspaceCompositionPaneRole,
  WorkspaceCompositionPaneSpec,
  WorkspaceCompositionSpec,
  WorkspacePaneAction,
  WorkspacePaneAlternativeRenderer,
  WorkspacePaneAvailability,
  WorkspacePaneAvailabilityAction,
  WorkspacePaneAvailabilityCapability,
  WorkspacePaneAvailabilityHealth,
  WorkspacePaneAvailabilityInput,
  WorkspacePaneAvailabilityPermission,
  WorkspacePaneAvailabilityPresence,
  WorkspacePaneAvailabilityReason,
  WorkspacePaneAvailabilityReasonCode,
  WorkspacePaneAvailabilityRequirements,
  WorkspacePaneAvailabilitySource,
  WorkspacePaneAvailabilityState,
  WorkspacePaneAvailabilityTelemetry,
  WorkspacePaneBoundContext,
  WorkspacePaneCatalog,
  WorkspacePaneCatalogInput,
  WorkspacePaneContextRequirement,
  WorkspacePaneContractVersion,
  WorkspacePaneDescriptor,
  WorkspacePaneDescriptorId,
  WorkspacePaneHostRegion,
  WorkspacePaneInstance,
  WorkspacePaneInstanceId,
  WorkspacePaneLayoutAdapterContext,
  WorkspacePaneLayoutDefinitionInput,
  WorkspacePaneLayoutTabAdaptation,
  WorkspacePaneLayoutTabAdapterOptions,
  WorkspacePaneLifecycle,
  WorkspacePaneLifecycleStage,
  WorkspacePaneMode,
  WorkspacePanePlacement,
  WorkspacePaneProvenance,
  WorkspacePaneProvenanceOrigin,
  WorkspacePaneRegion,
  WorkspacePaneRendererCandidate,
  WorkspacePaneRendererCapability,
  WorkspacePaneRendererId,
  WorkspacePaneRendererRef,
  WorkspacePaneRendererSelection,
  WorkspacePaneRendererSelectionOptions,
  WorkspacePaneStandardDataRendererRef,
  WorkspacePaneStateKey,
  WorkspacePaneSuppliableContexts,
} from '@kontourai/station-contracts';
export {
  cloneWorkspacePaneInitialArguments,
  createWorkspacePaneCatalog,
  createWorkspacePaneCatalogFromAdaptations,
  enumerateLayoutDefinitionPanes,
  enumerateLayoutPanes,
  instantiateWorkspaceComposition,
  isBoundedWorkspacePanePreviewImage,
  layoutTabFromWorkspacePaneAdaptation,
  MAX_WORKSPACE_COMPOSITION_CAPABILITIES,
  MAX_WORKSPACE_COMPOSITION_PANES,
  MAX_WORKSPACE_PANE_IDENTITY_SEGMENT_LENGTH,
  MAX_WORKSPACE_PANE_JSON_DEPTH,
  mcpAppHostAvailableDisplayModes,
  mediateMcpAppDisplayMode,
  paneAdaptationFromLayoutTab,
  parseWorkspaceCompositionSpec,
  parseWorkspacePaneBoundContext,
  parseWorkspacePaneContextRequirement,
  parseWorkspacePaneDescriptor,
  parseWorkspacePaneInstance,
  parseWorkspacePaneLayoutTabAdaptation,
  selectWorkspacePaneRenderer,
  toWorkspacePaneDescriptorId,
  toWorkspacePaneInstanceId,
  toWorkspacePaneRendererId,
  toWorkspacePaneStateKey,
  WORKSPACE_COMPOSITION_SPEC_VERSION,
  WORKSPACE_PANE_CONTRACT_VERSION,
  WORKSPACE_PANE_REGIONS,
  withWorkspacePaneInstanceLayoutBinding,
  workspacePaneModesSatisfiableBy,
} from '@kontourai/station-contracts';
export {
  resolveWorkspacePaneAvailability,
  toWorkspacePaneAvailabilityTelemetry,
} from '@kontourai/station-contracts/workspace-pane-availability';
export type {
  WorkspacePaneHostActionCatalog,
  WorkspacePaneHostActionExecution,
  WorkspacePaneHostActionPrepareRequest,
} from '@kontourai/station-contracts/workspace-pane-host-contribution';
export type {
  ProjectWorkspacePaneAvailabilityProjection,
  ProjectWorkspacePaneCatalog,
} from './client/projects';
export {
  useWorkspacePaneHostActionMutation,
  useWorkspacePaneHostActionsQuery,
} from './query-domains/workspacePaneHostActions';
// Catalog data is opt-in with the Pane contract so the root SDK namespace
// bridge does not pull this query into every Station UI bundle.
export { useProjectWorkspacePanesQuery } from './query-domains/workspaceProjects';
