#!/bin/sh
set -eu

REPOSITORY="kontourai/station"
ASSET_NAME="station-portable.tar.gz"
CHECKSUM_NAME="${ASSET_NAME}.sha256"
INSTALL_ROOT_MARKER='.station-portable-install-root'
DATA_ROOT_MARKER='.station-portable-data-root'
INSTALL_ROOT_SIGNATURE='station-portable-install-root-v1'
DATA_ROOT_SIGNATURE='station-portable-data-root-v1'
# A prebuilt server archive (#2675) carries this marker at its root, with
# exactly this content (scripts/lib/portable-server-archive.mjs writes it and
# packages/cli/src/commands/lifecycle-code-root.ts reads it).
PREBUILT_ARCHIVE_MARKER='.station-prebuilt-archive'
PREBUILT_ARCHIVE_SIGNATURE='station-prebuilt-archive-v1'
# The launcher protocol of the launcher this installer writes for a prebuilt
# archive: exec <current>/bin/station with the channel environment exported.
# A signed manifest names the protocol range its release supports.
INSTALLER_LAUNCHER_PROTOCOL=1
# The oldest host Node.js this script uses to verify and extract a prebuilt
# archive. (A source release is built on the host and needs Node.js 24.)
MINIMUM_VERIFIER_NODE_MAJOR=20

# Public-manifest signing keys, pinned into this script so `curl | sh` needs no
# second download to learn whom to trust.
# BEGIN GENERATED PINNED MANIFEST SIGNING KEYS
# Generated by scripts/install-script-generated.mjs from config/release-manifest-keys.json
# (JSON.stringify of its content). Do not edit by hand.
PINNED_MANIFEST_SIGNING_KEYS='{"keys":[{"keyId":"station-portable-nightly-2026-09","algorithm":"ed25519","publicKeySpkiPem":"-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAH74uCwGmcJFftH+reVCJjJysQRRON2k0mTUoDBf14OM=\n-----END PUBLIC KEY-----\n","channels":["nightly"]},{"keyId":"station-portable-release-2026-09","algorithm":"ed25519","publicKeySpkiPem":"-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAk8YKOCVgKcXsNNMjkGwYOfE53pV1zrajakwI91oxbPo=\n-----END PUBLIC KEY-----\n","channels":["stable","preview"]}]}'
# END GENERATED PINNED MANIFEST SIGNING KEYS

# Per-channel install constants (ring <-> runtime mapping, ports, launcher).
# BEGIN GENERATED CHANNEL CONSTANTS
# Generated by scripts/install-script-generated.mjs from config/channel-ports.json.
# Do not edit by hand. RELEASE_RINGS_JSON is the installable ring table:
# each ring, the runtime channel it installs as, and whether it is a
# prerelease (tags vX.Y.Z-<ring>.N) or the one unlabelled ring (vX.Y.Z).
INSTALLABLE_RUNTIME_CHANNELS='stable beta nightly'
RELEASE_RINGS_JSON='{"stable":{"runtimeChannel":"stable","prerelease":false},"preview":{"runtimeChannel":"beta","prerelease":true},"nightly":{"runtimeChannel":"nightly","prerelease":true}}'
# Sets the per-runtime-channel install constants; fails for a channel that
# no installable ring installs as.
channel_constants() {
  case "$1" in
    stable)
      runtime_release_channel=stable
      runtime_server_port=18141
      runtime_ui_port=18000
      runtime_launcher_name=station
      ;;
    beta)
      runtime_release_channel=preview
      runtime_server_port=28141
      runtime_ui_port=28000
      runtime_launcher_name=station-beta
      ;;
    nightly)
      runtime_release_channel=nightly
      runtime_server_port=38141
      runtime_ui_port=38000
      runtime_launcher_name=station-nightly
      ;;
    *) return 1 ;;
  esac
}
# END GENERATED CHANNEL CONSTANTS

# BEGIN GENERATED PORTABLE SERVER TARGETS
# Generated by scripts/install-script-generated.mjs from
# packages/shared/src/portable-server-targets.mjs. Do not edit by hand.
# Every platform a prebuilt server archive is published for, and its format.
PORTABLE_SERVER_TARGETS_JSON='[{"os":"darwin","arch":"arm64","format":"tar.gz"},{"os":"darwin","arch":"x64","format":"tar.gz"},{"os":"linux","arch":"arm64","format":"tar.gz"},{"os":"linux","arch":"x64","format":"tar.gz"},{"os":"win32","arch":"x64","format":"zip"}]'
# END GENERATED PORTABLE SERVER TARGETS

# BEGIN GENERATED NODE RUNTIME PINS
# Generated by scripts/install-script-generated.mjs from
# config/portable-server-node-runtime.json. Do not edit by hand. The official
# Node.js distribution for each POSIX archive target, pinned by digest.
PINNED_NODE_VERSION='24.21.0'
PINNED_NODE_ORIGIN='https://nodejs.org/dist/v24.21.0/'
# Sets pinned_node_file and pinned_node_sha256 for <os>-<arch>; fails for a
# target with no pinned tar.gz distribution.
pinned_node_distribution() {
  case "$1" in
    darwin-arm64)
      pinned_node_file='node-v24.21.0-darwin-arm64.tar.gz'
      pinned_node_sha256=bed7eea5325e1108f32ce5228ddd6a5f0f08a499ee42aa7442aea583702f6057
      ;;
    darwin-x64)
      pinned_node_file='node-v24.21.0-darwin-x64.tar.gz'
      pinned_node_sha256=1462cb3b3046b815cf8ea436d3da450ec1a9f11dac7e5a46b0ada5305d7e8097
      ;;
    linux-arm64)
      pinned_node_file='node-v24.21.0-linux-arm64.tar.gz'
      pinned_node_sha256=724282c3b43aec998aa9527380465b45d229e021b58035f5f4f63095eabfe5d5
      ;;
    linux-x64)
      pinned_node_file='node-v24.21.0-linux-x64.tar.gz'
      pinned_node_sha256=6e1db87ef58b8819e5d5402eff1536491b18edd8eb7bee5ef7897876e88dc5ff
      ;;
    *) return 1 ;;
  esac
}
# END GENERATED NODE RUNTIME PINS

fail() {
  printf 'Station install failed: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

default_bin_dir() {
  printf '%s/.local/bin\n' "$HOME"
}

install_root_was_requested=false
if [ -n "${STATION_INSTALL_ROOT+x}" ]; then install_root_was_requested=true; fi
requested_runtime_channel="${STATION_CHANNEL:-stable}"
# `preview` is a ring, not a runtime; it was once accepted as a runtime name.
if [ "$requested_runtime_channel" = preview ]; then
  fail 'STATION_CHANNEL=preview is a legacy unqualified channel; rerun with STATION_CHANNEL=beta (or install stable with STATION_CHANNEL=stable)'
fi
channel_constants "$requested_runtime_channel" || \
  fail "STATION_CHANNEL must be one of: $INSTALLABLE_RUNTIME_CHANNELS"


sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{ print $1 }'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{ print $1 }'
  else
    fail 'sha256sum or shasum is required'
  fi
}

# The <os>-<arch> of this host, spelled as Node.js does (process.platform and
# process.arch), so it names a prebuilt archive target and a pinned Node.js.
host_target() {
  case "$(uname -s)" in
    Darwin) host_os=darwin ;;
    Linux) host_os=linux ;;
    *) fail "unsupported operating system: $(uname -s)" ;;
  esac
  case "$(uname -m)" in
    x86_64|amd64) host_arch=x64 ;;
    arm64|aarch64) host_arch=arm64 ;;
    *) fail "unsupported processor architecture: $(uname -m)" ;;
  esac
  # A shell translated by Rosetta reports x86_64 on Apple silicon.
  if [ "$host_os" = darwin ] && [ "$host_arch" = x64 ] && \
    [ "$(sysctl -n sysctl.proc_translated 2>/dev/null || true)" = 1 ]; then
    host_arch=arm64
  fi
  printf '%s-%s\n' "$host_os" "$host_arch"
}

tmp_root="$(mktemp -d "${TMPDIR:-/tmp}/station-install.XXXXXX")"
state_stage=""
gh_config_dir="$tmp_root/gh-config"
build_home="$tmp_root/build-home"
mkdir -m 700 "$gh_config_dir" "$build_home"
cleanup() {
  if [ -n "$state_stage" ]; then
    rm -f "$state_stage"
  fi
  if [ -n "${staged_launcher:-}" ]; then
    rm -f "$staged_launcher"
  fi
  # The release build intentionally receives an inaccessible GitHub config.
  # Restore owner traversal only inside our private temporary root so the trap
  # can remove it without weakening the build-time credential boundary.
  chmod -R u+rwx "$tmp_root" 2>/dev/null || true
  rm -rf "$tmp_root"
}
trap cleanup EXIT HUP INT TERM

# `node` is the one portable authority for resolving filesystem aliases and
# for verifying a signed manifest, so it is settled before anything else. A
# prebuilt archive brings its own Node.js to RUN Station, but that Node.js
# cannot vouch for the manifest that names it. In order of preference:
#   host     a Node.js on PATH, MINIMUM_VERIFIER_NODE_MAJOR or newer;
#   installed  the Node.js inside this channel's installed archive, verified
#            when it was installed (it is what the launcher already runs), so
#            `station upgrade` and uninstall need no host Node.js and no
#            download;
#   pinned   the official Node.js distribution pinned above by sha256,
#            downloaded into the private temporary directory and used only to
#            verify and extract. Only uninstall and the public-manifest path
#            (which can install a prebuilt archive) download it.
# A source release is different: it is built on this host and later run by
# the host Node.js, so that path requires the host Node.js 24 (checked below).
node_is_adequate() {
  node_probe_major="$("$1" -p 'process.versions.node.split(".")[0]' 2>/dev/null)" || return 1
  case "$node_probe_major" in ''|*[!0-9]*) return 1 ;; esac
  [ "$node_probe_major" -ge "$MINIMUM_VERIFIER_NODE_MAJOR" ]
}

download_pinned_node() {
  node_target="$(host_target)"
  pinned_node_distribution "$node_target" || \
    fail "no pinned Node.js distribution for $node_target; install Node.js $MINIMUM_VERIFIER_NODE_MAJOR or newer and rerun"
  require_command curl
  require_command tar
  node_distribution="$tmp_root/$pinned_node_file"
  printf 'Downloading Node.js %s to verify this install (no Node.js %s or newer on PATH)...\n' \
    "$PINNED_NODE_VERSION" "$MINIMUM_VERIFIER_NODE_MAJOR"
  curl -fsSL --retry 3 --retry-connrefused --connect-timeout 10 -o "$node_distribution" -- \
    "$PINNED_NODE_ORIGIN$pinned_node_file" || fail "could not download $pinned_node_file"
  [ "$(sha256_of "$node_distribution")" = "$pinned_node_sha256" ] || \
    fail "$pinned_node_file does not match its pinned sha256"
  node_directory="${pinned_node_file%.tar.gz}"
  mkdir -m 700 "$tmp_root/node"
  tar -xzf "$node_distribution" -C "$tmp_root/node" "$node_directory/bin/node" || \
    fail "could not extract $pinned_node_file"
  rm -f "$node_distribution"
  PATH="$tmp_root/node/$node_directory/bin:$PATH"
  export PATH
  node_is_adequate node || fail "the pinned Node.js $PINNED_NODE_VERSION does not run on this host"
}

verifier_node_source=host
if ! command -v node >/dev/null 2>&1 || ! node_is_adequate node; then
  installed_node="${STATION_INSTALL_ROOT:-${STATION_ROOT:-$HOME/.station}/installs/$requested_runtime_channel}/current/runtime/bin/node"
  if [ -f "$installed_node" ] && [ -x "$installed_node" ] && node_is_adequate "$installed_node"; then
    # Run a private copy: the version directory it lives in can be renamed
    # (an explicit same-version replacement moves it aside) or pruned while
    # this script still needs `node`.
    mkdir -m 700 "$tmp_root/installed-node"
    cp "$installed_node" "$tmp_root/installed-node/node" || \
      fail 'could not copy the installed Station Node.js'
    chmod 700 "$tmp_root/installed-node/node"
    PATH="$tmp_root/installed-node:$PATH"
    export PATH
    node_is_adequate node || fail 'the installed Station Node.js does not run from its copy'
    verifier_node_source=installed
  elif [ "${1:-install}" = uninstall ] || \
    { [ "${1:-install}" = install ] && [ -n "${STATION_INSTALL_PUBLIC_MANIFEST_URL:-}" ]; }; then
    download_pinned_node
    verifier_node_source=pinned
  else
    # The authenticated GitHub-release path installs only source releases,
    # which need the host Node.js 24 anyway.
    require_command node
    fail "Node.js 24 is required; found $(node --version)"
  fi
fi

normalized_station_root() {
  node -e '
    const [raw, fallback] = process.argv.slice(1);
    process.stdout.write(raw.trim() || fallback);
  ' "${STATION_ROOT:-}" "$HOME/.station"
}

configure_runtime_paths() {
  runtime_channel="$1"
  channel_constants "$runtime_channel" || \
    fail "unsupported verified runtime channel: $runtime_channel"
  station_root="$(normalized_station_root)" || fail 'STATION_ROOT is invalid'
  install_root="${STATION_INSTALL_ROOT:-$station_root/installs/$runtime_channel}"
  bin_dir="${STATION_BIN_DIR:-$(default_bin_dir)}"
  station_home="${STATION_HOME:-$station_root/instances/$runtime_channel}"
  current_link="$install_root/current"
  launcher="$bin_dir/$runtime_launcher_name"
  state_file="$install_root/.station-release-state.json"
}

# A verified release determines the runtime identity.  Once that identity is
# known, use one port resolution for both the pre-promotion build and the
# supervised start.  Keeping this here avoids producing assets for one port
# pair and booting them with another.
# An explicit port wins; otherwise the ports this install recorded (a custom
# port survives an upgrade that does not repeat it, #2675), then the channel's.
recorded_server_port=""
recorded_ui_port=""
resolve_runtime_flags() {
  resolved_server_port="${STATION_INSTALL_SERVER_PORT:-${STATION_SERVER_PORT:-${recorded_server_port:-$runtime_server_port}}}"
  resolved_ui_port="${STATION_INSTALL_UI_PORT:-${STATION_UI_PORT:-${recorded_ui_port:-$runtime_ui_port}}}"
  for resolved_port in "$resolved_server_port" "$resolved_ui_port"; do
    case "$resolved_port" in
      ''|0*|*[!0-9]*) fail "invalid Station port: $resolved_port" ;;
    esac
    [ "${#resolved_port}" -le 5 ] && [ "$resolved_port" -le 65535 ] || \
      fail "invalid Station port: $resolved_port"
  done
}

# Uninstall has no release manifest to verify. Its channel therefore comes only
# from the invoking wrapper (or stable's explicit default), never from a stale
# unqualified preview state.
configure_runtime_paths "$requested_runtime_channel"

normalize_runtime_paths() {
  raw_station_home="$station_home"
  raw_install_root="$install_root"
  station_root="$(canonicalize_path "$station_root")" || fail 'STATION_ROOT is invalid'
  station_home="$(canonicalize_path "$station_home")" || fail 'STATION_HOME is invalid'
  install_root="$(canonicalize_path "$install_root")" || fail 'STATION_INSTALL_ROOT is invalid'
  bin_dir="$(canonicalize_path "$bin_dir")" || fail 'STATION_BIN_DIR is invalid'
  node -e '
    const fs = require("node:fs");
    const path = require("node:path");
    const [rawHome, rawInstall, root, home, install, rawBin, channel] = process.argv.slice(1);
    const fold = (value) => process.platform === "darwin" ? value.toLowerCase() : value;
    const same = (left, right) => fold(left) === fold(right);
    const inside = (child, parent) => {
      const normalizedChild = fold(child), normalizedParent = fold(parent);
      return normalizedChild === normalizedParent || normalizedChild.startsWith(`${normalizedParent}${path.sep}`);
    };
    const inspectDirectory = (target) => {
      let info;
      try { info = fs.lstatSync(target); } catch (error) {
        if (error && error.code === "ENOENT") return;
        throw error;
      }
      if (!info.isDirectory() || info.isSymbolicLink()) process.exit(2);
    };
    const rejectSelectedLeafLink = (target) => {
      try { if (fs.lstatSync(target).isSymbolicLink()) process.exit(3); }
      catch (error) { if (!error || error.code !== "ENOENT") throw error; }
    };
    inspectDirectory(root);
    for (const name of ["config", "cache", "installs", "instances"])
      inspectDirectory(path.join(root, name));
    inspectDirectory(path.join(root, "instances", "dev"));
    rejectSelectedLeafLink(rawHome);
    rejectSelectedLeafLink(rawInstall);
    if (same(home, root) ||
        ["config", "cache", "installs"].some((name) => inside(home, path.join(root, name))) ||
        same(home, path.join(root, "instances")) ||
        same(home, path.join(root, "instances", "dev"))) process.exit(4);
    const verifiedLeaf = path.join(root, "installs", channel);
    if (inside(install, root) && !same(install, verifiedLeaf)) process.exit(5);
    if (inside(root, home) || inside(root, install)) process.exit(6);
    void rawBin;
  ' "$raw_station_home" "$raw_install_root" "$station_root" "$station_home" "$install_root" "$bin_dir" "$runtime_channel" || \
    fail 'Station runtime paths are invalid, protected, or contain an unsafe selected link'
  current_link="$install_root/current"
  launcher="$bin_dir/$runtime_launcher_name"
  state_file="$install_root/.station-release-state.json"
}

canonicalize_path() {
  node -e '
    const fs = require("node:fs");
    const path = require("node:path");
    const absolute = path.resolve(process.argv[1]);
    const parsed = path.parse(absolute);
    let cursor = parsed.root;
    const segments = absolute.slice(parsed.root.length).split(path.sep).filter(Boolean);
    for (let index = 0; index < segments.length; index += 1) {
      const next = path.join(cursor, segments[index]);
      let info;
      try { info = fs.lstatSync(next); } catch (error) {
        if (error && error.code === "ENOENT") {
          process.stdout.write(path.resolve(cursor, ...segments.slice(index)));
          process.exit(0);
        }
        throw error;
      }
      cursor = info.isSymbolicLink() ? fs.realpathSync(next) : next;
    }
    process.stdout.write(path.resolve(cursor));
  ' "$1"
}

# Freeze all persisted and launched roots before any later cwd change.
normalize_runtime_paths

# The owned launcher, in one of two exact texts: v1 runs a source release's
# `<current>/station`, v2 a prebuilt archive's `<current>/bin/station`. Either
# is recognized as this install's own, so an upgrade between the layouts and
# uninstall both keep working; anything else is someone else's file.
LAUNCHER_TEXT_JS='
  const sq = String.fromCharCode(39);
  const q = (value) => sq + value.split(sq).join(`${sq}"${sq}"${sq}`) + sq;
  const launcherText = (kind, channel, stationRoot, home, root, current) => [
    "#!/bin/sh", kind === "archive" ? "# station-owned-launcher-v2" : "# station-owned-launcher-v1",
    `export STATION_CHANNEL=${q(channel)}`,
    `export STATION_ROOT=${q(stationRoot)}`,
    `export STATION_HOME=${q(home)}`,
    `export STATION_INSTALL_ROOT=${q(root)}`,
    `exec ${q(kind === "archive" ? `${current}/bin/station` : `${current}/station`)} "$@"`, ""
  ].join("\n");
'

launcher_is_owned() {
  [ -f "$launcher" ] && [ ! -L "$launcher" ] || return 1
  node -e "$LAUNCHER_TEXT_JS"'
    const fs = require("node:fs");
    const [path, ...identity] = process.argv.slice(1);
    const text = fs.readFileSync(path, "utf8");
    if (!["source", "archive"].some((kind) => text === launcherText(kind, ...identity))) process.exit(1);
  ' "$launcher" "$runtime_channel" "$station_root" "$station_home" "$install_root" "$current_link"
}

assert_launcher_safe() {
  if [ -e "$launcher" ] || [ -L "$launcher" ]; then
    launcher_is_owned || fail "refusing to replace a launcher not owned by the $runtime_channel install: $launcher"
  fi
}

write_staged_launcher() {
  staged_launcher="$bin_dir/.station-launcher-$runtime_channel.$$"
  rm -f "$staged_launcher"
  node -e "$LAUNCHER_TEXT_JS"'
    const fs = require("node:fs");
    const [path, kind, ...identity] = process.argv.slice(1);
    const text = launcherText(kind, ...identity);
    fs.writeFileSync(path, text, { encoding: "utf8", mode: 0o755, flag: "wx" });
    fs.chmodSync(path, 0o755);
    const fd = fs.openSync(path, "r"); try { fs.fsyncSync(fd); } finally { fs.closeSync(fd); }
  ' "$staged_launcher" "$release_kind" "$runtime_channel" "$station_root" "$station_home" "$install_root" "$current_link" || \
    fail 'could not stage the channel launcher'
}

launcher_points_to_current() {
  launcher_is_owned
}

assert_safe_remove_target() {
  target="$1"
  [ -n "$target" ] || fail 'refusing to remove an empty path'
  [ ! -L "$target" ] || fail "refusing to remove a symlinked root: $target"
  if [ -e "$target" ]; then
    node -e '
      const fs = require("node:fs");
      const info = fs.lstatSync(process.argv[1]);
      if (typeof process.getuid === "function" && info.uid !== process.getuid()) {
        process.exit(1);
      }
    ' "$target" || fail "refusing to remove a root owned by another user: $target"
  fi
  canonical_target="$(canonicalize_path "$target")"
  canonical_home="$(canonicalize_path "$HOME")"
  case "$canonical_home/" in
    "$canonical_target/"*) fail "refusing to remove HOME or its ancestor: $target" ;;
  esac
  [ "$canonical_target" != "/" ] || fail 'refusing to remove /'
}

assert_roots_do_not_overlap() {
  canonical_install_root="$(canonicalize_path "$install_root")"
  canonical_station_home="$(canonicalize_path "$station_home")"
  case "$canonical_station_home/" in
    "$canonical_install_root/"*)
      fail 'STATION_HOME and STATION_INSTALL_ROOT must not overlap so uninstall can preserve data'
      ;;
  esac
  case "$canonical_install_root/" in
    "$canonical_station_home/"*)
      fail 'STATION_HOME and STATION_INSTALL_ROOT must not overlap so uninstall can preserve data'
      ;;
  esac
}

# The installer owns exactly one channel leaf. It must never claim a shared
# root or container, even when STATION_HOME is deliberately outside the root:
# uninstall removes INSTALL_ROOT and must not be able to erase profiles,
# another runtime, cache, or all channel installs.
assert_install_root_is_channel_leaf() {
  canonical_install_root="$(canonicalize_path "$install_root")"
  canonical_station_root="$(canonicalize_path "$station_root")"
  for shared in \
    "$canonical_station_root" \
    "$canonical_station_root/config" \
    "$canonical_station_root/instances" \
    "$canonical_station_root/cache" \
    "$canonical_station_root/installs"; do
    case "$shared/" in
      "$canonical_install_root/"*)
        fail "STATION_INSTALL_ROOT must be a channel leaf, not a Station shared root or container: $install_root"
        ;;
    esac
  done
  for protected in \
    "$canonical_station_root/config" \
    "$canonical_station_root/instances" \
    "$canonical_station_root/cache"; do
    case "$canonical_install_root/" in
      "$protected/"*)
        fail "STATION_INSTALL_ROOT must not be inside protected Station data: $install_root"
        ;;
    esac
  done
  expected_channel_leaf="$canonical_station_root/installs/$runtime_channel"
  case "$canonical_install_root" in
    "$canonical_station_root/installs"|"$canonical_station_root/installs/"*)
      [ "$canonical_install_root" = "$expected_channel_leaf" ] || \
        fail "STATION_INSTALL_ROOT must be the verified $runtime_channel channel leaf: $install_root"
      ;;
  esac
}

prepare_owned_root() {
  root="$1"
  marker_name="$2"
  signature="$3"
  existing_policy="$4"
  node -e '
    const fs = require("node:fs");
    const path = require("node:path");
    const [root, markerName, signature, existingPolicy] = process.argv.slice(1);
    const owner = typeof process.getuid === "function" ? process.getuid() : null;
    if (!fs.existsSync(root)) fs.mkdirSync(root, { recursive: true, mode: 0o700 });
    const rootInfo = fs.lstatSync(root);
    if (!rootInfo.isDirectory() || rootInfo.isSymbolicLink() ||
        (owner !== null && rootInfo.uid !== owner) ||
        (rootInfo.mode & 0o022) !== 0) process.exit(2);
    const marker = path.join(root, markerName);
    if (fs.existsSync(marker)) {
      const info = fs.lstatSync(marker);
      if (!info.isFile() || info.isSymbolicLink() ||
          (owner !== null && info.uid !== owner) ||
          (info.mode & 0o077) !== 0 ||
          fs.readFileSync(marker, "utf8") !== `${signature}\n`) process.exit(3);
      process.stdout.write("managed");
      process.exit(0);
    }
    if (fs.readdirSync(root).length > 0) {
      if (existingPolicy === "preserve") {
        process.stdout.write("preserved");
        process.exit(0);
      }
      process.exit(4);
    }
    const fd = fs.openSync(marker, "wx", 0o600);
    try {
      fs.writeFileSync(fd, `${signature}\n`);
      fs.fsyncSync(fd);
    } finally {
      fs.closeSync(fd);
    }
    process.stdout.write("managed");
  ' "$root" "$marker_name" "$signature" "$existing_policy"
}

prepare_safe_directory() {
  directory="$1"
  node -e '
    const fs = require("node:fs");
    const directory = process.argv[1];
    const owner = typeof process.getuid === "function" ? process.getuid() : null;
    if (!fs.existsSync(directory)) fs.mkdirSync(directory, { recursive: true, mode: 0o700 });
    const info = fs.lstatSync(directory);
    if (!info.isDirectory() || info.isSymbolicLink() ||
        (owner !== null && info.uid !== owner) ||
        (info.mode & 0o022) !== 0) process.exit(1);
  ' "$directory" || fail "directory must be same-user and not group/world writable: $directory"
}

assert_owned_root() {
  root="$1"
  marker_name="$2"
  signature="$3"
  node -e '
    const fs = require("node:fs");
    const path = require("node:path");
    const [root, markerName, signature] = process.argv.slice(1);
    const owner = typeof process.getuid === "function" ? process.getuid() : null;
    const rootInfo = fs.lstatSync(root);
    const marker = path.join(root, markerName);
    const markerInfo = fs.lstatSync(marker);
    if (!rootInfo.isDirectory() || rootInfo.isSymbolicLink() ||
        !markerInfo.isFile() || markerInfo.isSymbolicLink() ||
        (owner !== null && (rootInfo.uid !== owner || markerInfo.uid !== owner)) ||
        fs.readFileSync(marker, "utf8") !== `${signature}\n`) process.exit(1);
  ' "$root" "$marker_name" "$signature" 2>/dev/null || \
    fail "refusing to remove a root not owned by this installer: $root"
}

safe_remove_tree() {
  target="$1"
  assert_safe_remove_target "$target"
  # An installed archive version is read-only; make it removable. chmod -R
  # does not follow symbolic links it meets inside the tree.
  if [ -d "$target" ]; then
    chmod -R u+w "$target" 2>/dev/null || true
  fi
  rm -rf "$target"
}

# The active release's own CLI: bin/station in a prebuilt archive, station in
# a source release.
try_stop_installed_station() {
  for installed_entry in "$current_link/bin/station" "$current_link/station"; do
    [ -f "$installed_entry" ] && [ -x "$installed_entry" ] || continue
    PATH="$current_link/node_modules/.bin:$PATH" \
      "$installed_entry" stop --base="$station_home" || return 1
    return 0
  done
}

stop_installed_station() {
  try_stop_installed_station || \
    fail 'could not stop the installed Station; no files were removed'
}

start_installed_station() {
  set -- start --base="$station_home" \
    "--port=$resolved_server_port" \
    "--ui-port=$resolved_ui_port"
  PATH="$current_link/node_modules/.bin:$PATH" "$launcher" "$@"
}

# Station user services that run this install root's `current` (#2675
# slice C): `station service install` from a prebuilt archive this installer
# made active records `kind: "archive"` and the install root in the service
# manifest under the home. Such a unit follows `current`, so an upgrade stops
# it, switches `current` and starts it again instead of starting Station
# beside it. The same rule as isArchiveServiceOfInstallRoot in the CLI's
# service-upgrade-guard.ts. A manifest that cannot be read might be one of
# them, so it stops the install.
#
# A unit keeps the ports it was installed with: install.sh restarts it, it
# does not rewrite it. So ports the caller names explicitly must be the
# unit's, or the upgrade refuses rather than silently ignoring them; ports
# that only come from the recorded state or the channel default do not
# constrain the unit. Arguments: the explicit server and UI ports, or none.
archive_services=""
active_services=""
list_archive_services() {
  [ -d "$station_home/service" ] || return 0
  node -e '
    const fs = require("node:fs");
    const path = require("node:path");
    const [dir, installRoot, serverPort, uiPort] = process.argv.slice(1);
    const real = (p) => { try { return fs.realpathSync(p); } catch { return p; } };
    const ids = [];
    for (const name of fs.readdirSync(dir).sort()) {
      if (!name.endsWith(".json")) continue;
      const file = path.join(dir, name);
      let manifest;
      try { manifest = JSON.parse(fs.readFileSync(file, "utf8")); } catch { manifest = null; }
      if (!manifest || typeof manifest !== "object" || Array.isArray(manifest)) {
        console.error(`unreadable Station service manifest: ${file}`);
        process.exit(1);
      }
      if (manifest.platform !== process.platform || manifest.kind !== "archive" ||
          typeof manifest.installRoot !== "string" ||
          real(manifest.installRoot) !== real(installRoot)) continue;
      const id = manifest.instanceId;
      if (typeof id !== "string" || `${id}.json` !== name || !/^[a-z0-9._][a-z0-9._-]*$/.test(id)) {
        console.error(`Station service manifest names an invalid instance: ${file}`);
        process.exit(1);
      }
      if (manifest.repoPath !== path.join(real(installRoot), "current") ||
          (serverPort !== "" &&
           (manifest.serverPort !== Number(serverPort) || manifest.uiPort !== Number(uiPort)))) {
        console.error(`Station service ${id} runs this install with a different command or ports than requested (it serves ports ${manifest.serverPort} and ${manifest.uiPort}); reinstall it with the intended ports, or omit the port variables, before upgrading`);
        process.exit(1);
      }
      ids.push(id);
    }
    process.stdout.write(ids.join(" "));
  ' "$station_home/service" "$install_root" "${1:-}" "${2:-}"
}

# The ports this run was explicitly asked for, as list_archive_services'
# arguments; nothing when neither port was named.
explicit_port_arguments() {
  if [ -n "${STATION_INSTALL_SERVER_PORT:-}${STATION_SERVER_PORT:-}${STATION_INSTALL_UI_PORT:-}${STATION_UI_PORT:-}" ]; then
    printf '%s %s' "$resolved_server_port" "$resolved_ui_port"
  fi
}

# Runs `station service <verb> --instance=<id>` with the active release's own
# CLI, against this install's home.
run_service_command() {
  service_verb="$1"
  service_instance="$2"
  shift 2
  for installed_entry in "$current_link/bin/station" "$current_link/station"; do
    [ -f "$installed_entry" ] && [ -x "$installed_entry" ] || continue
    STATION_ROOT="$station_root" STATION_HOME="$station_home" \
      "$installed_entry" service "$service_verb" "--instance=$service_instance" \
      "--base=$station_home" "$@"
    return
  done
  return 1
}

# Prints `active` or `inactive` for a service's unit; fails when the service
# backend cannot say.
service_unit_state() {
  service_status="$(run_service_command status "$1" --json)" || true
  printf '%s' "$service_status" | node -e '
    let text = "";
    process.stdin.on("data", (chunk) => { text += chunk; });
    process.stdin.on("end", () => {
      let value;
      try { value = JSON.parse(text); } catch { process.exit(1); }
      const active = value?.unit?.active;
      if (active === true) process.stdout.write("active");
      else if (active === false) process.stdout.write("inactive");
      else process.exit(1);
    });
  '
}

# The service answers its identity probes as the release just installed.
service_runs_release() {
  service_status="$(run_service_command status "$1" --json)" || true
  printf '%s' "$service_status" | node -e '
    let text = "";
    process.stdin.on("data", (chunk) => { text += chunk; });
    process.stdin.on("end", () => {
      let value;
      try { value = JSON.parse(text); } catch { process.exit(1); }
      if (value?.instance?.healthy !== true || value.instance.sha !== process.argv[1]) process.exit(1);
    });
  ' "$release_sha"
}

# Stops, then starts, each named service with the active release's CLI, so a
# generation of another version that is still up is replaced, not adopted.
restart_services() {
  for restart_id in $1; do
    run_service_command stop "$restart_id" >/dev/null || return 1
    run_service_command start "$restart_id" >/dev/null || return 1
  done
}

# Stops what runs from the active release before `current` moves. With a
# running service, the service is stopped through its manager: stopping only
# its Station would make the manager restart it mid-switch (#2674).
stop_for_switch() {
  [ -n "$active_services" ] || { stop_installed_station; return 0; }
  stopped_services=""
  for stop_id in $active_services; do
    if ! run_service_command stop "$stop_id" >/dev/null; then
      restart_services "$stopped_services" || true
      fail "could not stop Station service $stop_id; the running release was not changed"
    fi
    stopped_services="$stopped_services $stop_id"
  done
  if ! try_stop_installed_station; then
    restart_services "$stopped_services" || true
    fail 'could not stop the installed Station; the running release was not changed'
  fi
}

# Starts the restored release again: the services that were running, or
# Station itself.
restart_previous_station() {
  if [ -n "$active_services" ]; then
    restart_services "$active_services" >/dev/null 2>&1
  else
    start_installed_station >/dev/null 2>&1
  fi
}

replace_link_atomically() {
  target="$1"
  destination="$2"
  pending="$install_root/.link.$$"
  rm -f "$pending"
  ln -s "$target" "$pending"
  node -e '
    const fs = require("node:fs");
    fs.renameSync(process.argv[1], process.argv[2]);
  ' "$pending" "$destination"
}

restore_previous_state() {
  if [ -f "$previous_state_backup" ]; then
    restore_stage="$install_root/.station-release-state.restore.$$"
    node -e '
      const fs = require("node:fs");
      const [source, stage, destination] = process.argv.slice(1);
      fs.copyFileSync(source, stage, fs.constants.COPYFILE_EXCL);
      fs.chmodSync(stage, 0o600);
      const fd = fs.openSync(stage, "r");
      try { fs.fsyncSync(fd); } finally { fs.closeSync(fd); }
      fs.renameSync(stage, destination);
    ' "$previous_state_backup" "$restore_stage" "$state_file" || return 1
  else
    rm -f "$state_file"
  fi
}

restore_previous_launcher() {
  if [ "$previous_launcher_present" = true ]; then
    restore_launcher_stage="$bin_dir/.station-launcher.restore.$$"
    node -e '
      const fs = require("node:fs");
      fs.copyFileSync(process.argv[1], process.argv[2], fs.constants.COPYFILE_EXCL);
      fs.chmodSync(process.argv[2], 0o755);
      fs.renameSync(process.argv[2], process.argv[3]);
    ' "$previous_launcher_backup" "$restore_launcher_stage" "$launcher" || return 1
  else
    rm -f "$launcher"
  fi
}

# Renames a directory that may be a sealed (read-only) archive version.
# Some filesystems refuse to rename a directory whose own write bit is clear
# (it would update the directory's `..`), so the top directory is made
# writable for the rename and sealed again at its new name. Nothing inside it
# changes. It fails only when the rename fails: callers depend on where the
# directory now is, so a failed re-seal is a warning, not a failure.
move_version_dir() {
  move_sealed=false
  if [ ! -w "$1" ]; then
    move_sealed=true
    chmod u+w "$1" || return 1
  fi
  if ! node -e 'require("node:fs").renameSync(process.argv[1], process.argv[2])' "$1" "$2"; then
    [ "$move_sealed" = false ] || chmod a-w "$1" 2>/dev/null || true
    return 1
  fi
  if [ "$move_sealed" = true ] && ! chmod a-w "$2"; then
    printf 'Warning: could not make %s read-only again after moving it.\n' "$2" >&2
  fi
  return 0
}

restore_previous_release() {
  if [ -n "${displaced_release:-}" ]; then
    # Put the moved-aside version back under its own name.
    if [ -e "$release_dir" ] || [ -L "$release_dir" ]; then
      safe_remove_tree "$release_dir" || return 1
    fi
    move_version_dir "$displaced_release" "$release_dir" || return 1
    previous_release="$release_dir"
    displaced_release=""
  fi
  if [ -n "$previous_release" ]; then
    replace_link_atomically "$previous_release" "$current_link" || return 1
    restore_previous_launcher || return 1
    restore_previous_state || return 1
    restart_previous_station || return 1
  else
    rm -f "$current_link" "$launcher"
    restore_previous_state || return 1
  fi
}

fail_with_rollback() {
  failure="$1"
  if restore_previous_release; then
    if [ -n "$previous_release" ]; then
      fail "$failure; the previous release was restored"
    fi
    fail "$failure; the incomplete install was removed"
  fi
  fail "$failure; automatic recovery also failed"
}

uninstall_station() {
  purge_data=false
  if [ "${1:-}" = "--purge-data" ]; then
    purge_data=true
  elif [ -n "${1:-}" ]; then
    fail "unknown uninstall option: $1"
  fi

  if [ -e "$install_root" ] || [ -L "$install_root" ]; then
    assert_safe_remove_target "$install_root"
    assert_owned_root "$install_root" "$INSTALL_ROOT_MARKER" "$INSTALL_ROOT_SIGNATURE"
  fi
  if [ "$purge_data" = true ] && { [ -e "$station_home" ] || [ -L "$station_home" ]; }; then
    assert_safe_remove_target "$station_home"
    assert_owned_root "$station_home" "$DATA_ROOT_MARKER" "$DATA_ROOT_SIGNATURE"
  fi

  # A service that runs this install's `current` would be left pointing at
  # nothing (#2675 slice C).
  uninstall_services="$(list_archive_services)" || \
    fail "cannot tell which Station services in $station_home/service run this install; nothing was removed"
  [ -z "$uninstall_services" ] || \
    fail "Station service(s) $uninstall_services run this install; remove each first with: $launcher service uninstall --instance=<name>. Nothing was removed"
  stop_installed_station
  if [ -e "$launcher" ] || [ -L "$launcher" ]; then
    launcher_is_owned || fail "refusing to remove a launcher not owned by the $runtime_channel install: $launcher"
    rm -f "$launcher"
  fi
  if [ -e "$install_root" ] || [ -L "$install_root" ]; then
    safe_remove_tree "$install_root"
  fi
  if [ "$purge_data" = true ] && { [ -e "$station_home" ] || [ -L "$station_home" ]; }; then
    safe_remove_tree "$station_home"
  fi

  printf 'Station uninstalled.\n'
  if [ "$purge_data" = false ]; then
    printf 'Data preserved at %s\n' "$station_home"
  fi
}

assert_safe_remove_target "$install_root"
assert_roots_do_not_overlap
assert_install_root_is_channel_leaf

case "${1:-install}" in
  install) ;;
  uninstall)
    shift
    uninstall_station "${1:-}"
    exit 0
    ;;
  *) fail "usage: install.sh [install|uninstall [--purge-data]]" ;;
esac

public_manifest_url="${STATION_INSTALL_PUBLIC_MANIFEST_URL:-}"
# Nightly is published only as a signed public manifest (#2675). The
# authenticated gh path below resolves `v*` GitHub releases, verifies
# attestations from release.yml, and maps only stable/preview tags; a nightly
# build is none of those, so that path cannot serve it and must not guess.
if [ "$requested_runtime_channel" = nightly ] && [ -z "$public_manifest_url" ]; then
  fail 'STATION_CHANNEL=nightly installs only from a signed public manifest; set STATION_INSTALL_PUBLIC_MANIFEST_URL (the authenticated GitHub-release path serves stable and beta only)'
fi

# Nightly coexistence (#2675). The Station Nightly desktop app defaults to the
# same runtime identity as a portable nightly install: the home
# $STATION_ROOT/instances/nightly and ports 38141/38000. The two are one
# channel runtime, so they cannot both run on a host with default settings,
# and a portable install must never silently adopt data another Station
# owns. Stable and beta desktop apps share their channels' defaults in the
# same way; this installer keeps its existing behavior for those channels.
assert_nightly_coexistence() {
  [ "$runtime_channel" = nightly ] || return 0
  # An explicit STATION_HOME is a deliberate choice (the owned launcher and
  # packaged `station upgrade` always pass one). Only the default home is
  # guarded: it must be absent, empty, or already carry this installer's
  # data-root marker.
  if [ -z "${STATION_HOME:-}" ]; then
    node -e '
      const fs = require("node:fs");
      const [home, markerName] = process.argv.slice(1);
      let entries;
      try { entries = fs.readdirSync(home); } catch (error) {
        if (error && error.code === "ENOENT") process.exit(0);
        throw error;
      }
      if (entries.length === 0 || entries.includes(markerName)) process.exit(0);
      process.exit(1);
    ' "$station_home" "$DATA_ROOT_MARKER" || \
      fail "$station_home already holds Station data this installer does not own (usually the Station Nightly desktop app's home). Refusing to share it silently: set STATION_HOME to that path to share it deliberately, or to another directory under $station_root/instances to keep separate data"
  fi
  # A port already in use when no portable nightly release is active cannot
  # be this install's own Station. (During an upgrade the running Station is
  # ours and is stopped before the new one starts.) Nothing binds a port when
  # the install does not start Station.
  if [ "${STATION_INSTALL_NO_START:-0}" != 1 ] && [ ! -L "$current_link" ]; then
    for probe_port in "$resolved_server_port" "$resolved_ui_port"; do
      node -e '
        const net = require("node:net");
        const socket = net.connect({ host: "127.0.0.1", port: Number(process.argv[1]) });
        socket.setTimeout(2000);
        socket.on("connect", () => { socket.destroy(); process.exit(3); });
        socket.on("timeout", () => { socket.destroy(); process.exit(4); });
        socket.on("error", (error) => process.exit(error.code === "ECONNREFUSED" ? 0 : 4));
      ' "$probe_port" || {
        probe_status=$?
        if [ "$probe_status" = 3 ]; then
          fail "port $probe_port is already in use on this host, and no portable nightly Station is installed to own it. The Station Nightly desktop app uses the same ports; quit it before installing, or install with STATION_INSTALL_NO_START=1 and start Station once the port is free"
        fi
        fail "could not determine whether port $probe_port is free"
      }
    done
  fi
}
resolve_runtime_flags
assert_nightly_coexistence

# A source release (the authenticated GitHub-release path, or a schema 1
# public manifest) installs its dependencies and builds on this host, then runs
# on the host Node.js, so it needs the host's Node.js 24 and npm. A prebuilt
# archive needs neither.
require_source_toolchain() {
  [ "$verifier_node_source" = host ] || \
    fail 'this release is a source release that is built on this host; it needs Node.js 24 and npm on PATH'
  require_command npm
  node_major="$(node -p 'process.versions.node.split(".")[0]')"
  [ "$node_major" = 24 ] || fail "Node.js 24.x is required; found $(node --version)"
}

if [ -n "$public_manifest_url" ]; then
  required_commands='curl tar'
else
  required_commands='curl tar gh'
fi
for command_name in $required_commands; do
  require_command "$command_name"
done
if [ -z "$public_manifest_url" ]; then
  require_source_toolchain
fi

export GH_CONFIG_DIR="$gh_config_dir"

previous_state_backup="$tmp_root/previous-release-state.json"
previous_launcher_backup="$tmp_root/previous-launcher"
previous_launcher_present=false
release_channel="$runtime_release_channel"
version="${STATION_VERSION:-latest}"
if [ "$version" != latest ]; then
  # An exact pin names its ring: vX.Y.Z-<ring>.N for a prerelease ring,
  # vX.Y.Z for the unlabelled one. Every ring accepts exact pins, since a
  # rollback (STATION_INSTALL_ALLOW_ROLLBACK=1) needs an exact target.
  version_release_channel="$(node -e '
    const [version, ringsJson] = process.argv.slice(1);
    const rings = JSON.parse(ringsJson);
    const match = /^v(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)(?:-([a-z]+)\.[1-9][0-9]*)?$/.exec(version);
    const ring = !match ? undefined : match[1] === undefined
      ? Object.keys(rings).find((name) => !rings[name].prerelease)
      : Object.hasOwn(rings, match[1]) && rings[match[1]].prerelease ? match[1] : undefined;
    if (!ring) process.exit(1);
    process.stdout.write(ring);
  ' "$version" "$RELEASE_RINGS_JSON")" || fail "invalid STATION_VERSION: $version"
  [ "$version_release_channel" = "$runtime_release_channel" ] || \
    fail "STATION_VERSION $version is a $version_release_channel release; it cannot be installed as STATION_CHANNEL=$requested_runtime_channel"
fi

if [ -n "$public_manifest_url" ]; then
  # Trust comes from the signing keys pinned above plus the sha256 that the
  # signed payload carries for the archive. A valid signature proves WHO
  # published a manifest (a holder of a pinned key, for a channel that key is
  # allowed to sign) and that the archive bytes are the ones they named. It
  # does NOT prove that this is the release you should get now: a host can
  # withhold updates or replay any older manifest that was ever signed. The
  # checks below bind the requested channel and refuse to move an existing
  # install backwards, but nothing bounds how stale a manifest may be, so a
  # fresh install (no current release) can still be served an old one.
  # Because origins add nothing to that, this path neither requires the
  # manifest, key, and archive to live on distinct origins nor downloads its
  # verification key.
  #
  # TODO(#2675, default-flip PR): decide on freshness before this path becomes
  # the default: enforce a maximum age on the signed publishedAt (which means
  # periodically re-signing stable) or record why not.
  #
  # STATION_INSTALL_MANIFEST_PUBLIC_KEY_URL is a TEST-ONLY override for
  # fixtures that cannot hold a pinned private key. It is refused unless
  # STATION_INSTALL_ALLOW_INSECURE_TEST_URLS=1. It substitutes only the
  # verification key bytes: the envelope's keyId must still name a pinned key,
  # and that key's channel authorization still applies.
  test_key_url="${STATION_INSTALL_MANIFEST_PUBLIC_KEY_URL:-}"
  allow_test_urls="${STATION_INSTALL_ALLOW_INSECURE_TEST_URLS:-0}"
  if [ -n "$test_key_url" ] && [ "$allow_test_urls" != 1 ]; then
    fail 'STATION_INSTALL_MANIFEST_PUBLIC_KEY_URL is a test-only override and requires STATION_INSTALL_ALLOW_INSECURE_TEST_URLS=1; public installs verify against the pinned signing keys'
  fi
  node -e '
    const allowTest = process.env.STATION_INSTALL_ALLOW_INSECURE_TEST_URLS === "1";
    for (const value of process.argv.slice(1)) {
      if (!value) continue;
      const url = new URL(value);
      if (url.protocol !== "https:" && !(allowTest && ["http:", "file:"].includes(url.protocol))) process.exit(1);
    }
  ' "$public_manifest_url" "$test_key_url" || \
    fail 'the public manifest URL must use HTTPS'
  manifest_file="$tmp_root/station-ecosystem-manifest.json"
  test_key_file=""
  # A signed manifest is a few kilobytes. curl 8.4.0 and newer stop at
  # 1 MiB; older curl enforces the cap only on a declared Content-Length.
  curl -fsSL --retry 3 --retry-connrefused --connect-timeout 10 --max-filesize 1048576 -o "$manifest_file" -- "$public_manifest_url" || \
    fail 'could not download public ecosystem manifest'
  if [ -n "$test_key_url" ]; then
    test_key_file="$tmp_root/station-ecosystem-manifest-test-key.pem"
    curl -fsSL --retry 3 --retry-connrefused --connect-timeout 10 -o "$test_key_file" -- "$test_key_url" || \
      fail 'could not download the test-only manifest verification key'
  fi
  # The verifier below mirrors packages/shared/src/release-manifest.mjs (the
  # signer's and the supervisor's copy) check for check and message for
  # message; scripts/__tests__/release-manifest-vectors.test.ts runs one golden
  # corpus through all three. It prints its reason on stderr and exits:
  #   2 unknown keyId, 3 key not authorized for the payload channel,
  #   4 signature did not verify, 5 artifact URL not a plain canonical URL,
  #   6 no archive for this host, 7 launcher protocol not supported,
  #   8 signed channel is not the requested one, anything else malformed.
  # Schema 2 names prebuilt per-platform server archives. Schema 1 is the
  # stable/preview source release (station-portable.tar.gz, built on the
  # host), kept as the fallback for rings that publish no archive yet; the
  # shared verifier does not accept it. Each verified value is written to its
  # own file, so no signed string can shift into another field on the way back
  # to the shell.
  manifest_values="$tmp_root/manifest-values"
  manifest_host_target="$(host_target)"
  node -e '
    const crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path");
    const [manifestFile,pinnedKeysJson,testKeyFile,valuesDir,ringsJson,targetsJson,hostTarget,expectedChannel,launcherProtocolText]=process.argv.slice(1);
    const allowTest=process.env.STATION_INSTALL_ALLOW_INSECURE_TEST_URLS==="1";
    class Refusal extends Error { constructor(message,code){ super(message); this.code=code; } }
    const refuse=(message,code=1)=>{ throw new Refusal(message,code); };
    const isObject=(v)=>Boolean(v)&&typeof v==="object"&&!Array.isArray(v);
    const exact=(v,keys)=>isObject(v)&&JSON.stringify(Object.keys(v).sort())===JSON.stringify(keys);
    const canonical=(v)=>Array.isArray(v)?`[${v.map(canonical).join(",")}]`:isObject(v)?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(",")}}`:JSON.stringify(v);
    // A URL that is exactly its own canonical href, with no control
    // characters, spaces, userinfo, query or fragment: new URL() silently
    // strips tabs and newlines, so anything else could fetch something other
    // than the signed string. HTTPS only, except under the test-only flag.
    const plainUrl=(value)=>{
      if (typeof value!=="string"||[...value].some((c)=>c<=" "||c==="\u007f")) return false;
      let url; try { url=new URL(value); } catch { return false; }
      return url.href===value&&(url.protocol==="https:"||(allowTest&&["http:","file:"].includes(url.protocol)))&&url.username===""&&url.password===""&&!value.includes("?")&&!value.includes("#");
    };
    const release="(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)";
    const rings=JSON.parse(ringsJson);
    const shapes=Object.fromEntries(Object.entries(rings).map(([ring,entry])=>[ring,new RegExp(`^${release}${entry.prerelease?`-${ring}\\.([1-9][0-9]*)`:""}$`)]));
    const targets=JSON.parse(targetsJson);
    const values={};
    const common=(p)=>{
      if (typeof p.sourceSha!=="string"||!/^[a-f0-9]{40}$/.test(p.sourceSha)) refuse("invalid source SHA");
      if (typeof p.publishedAt!=="string"||Number.isNaN(new Date(p.publishedAt).getTime())||new Date(p.publishedAt).toISOString()!==p.publishedAt) refuse("invalid publication timestamp");
    };
    const verifyV1=(p)=>{
      if (!exact(p,["artifacts","channel","publishedAt","releaseTag","schemaVersion","sourceSha","version"])) refuse("manifest payload has an unexpected shape");
      if (!["stable","preview"].includes(p.channel)) refuse("invalid manifest channel");
      if (typeof p.version!=="string"||!shapes[p.channel].test(p.version)) refuse("manifest channel does not match release tag");
      if (p.releaseTag!==`v${p.version}`) refuse("release tag does not match version");
      common(p);
      if (!exact(p.artifacts,["macos","portable"])) refuse("invalid artifact set");
      const a=p.artifacts.portable;
      if (!exact(a,["name","sha256","url"])||a.name!=="station-portable.tar.gz"||typeof a.sha256!=="string"||!/^[a-f0-9]{64}$/.test(a.sha256)) refuse("invalid portable artifact descriptor");
      if (!plainUrl(a.url)) refuse("portable artifact url is not a canonical HTTPS URL",5);
      Object.assign(values,{kind:"source",url:a.url,sha256:a.sha256});
    };
    const verifyV2=(p)=>{
      if (!exact(p,["artifacts","channel","launcherProtocol","nodeVersion","publishedAt","releaseTag","schemaVersion","sourceSha","version"])) refuse("manifest payload has an unexpected shape");
      if (typeof p.channel!=="string"||!Object.hasOwn(shapes,p.channel)) refuse("invalid manifest channel");
      if (typeof p.version!=="string") refuse("invalid manifest version");
      if (!shapes[p.channel].test(p.version)) refuse("manifest channel does not match version");
      if (p.releaseTag!==`v${p.version}`) refuse("release tag does not match version");
      common(p);
      if (typeof p.nodeVersion!=="string"||!new RegExp(`^${release}$`).test(p.nodeVersion)) refuse("invalid Node.js version");
      const lp=p.launcherProtocol;
      if (!exact(lp,["max","min"])||!Number.isSafeInteger(lp.min)||!Number.isSafeInteger(lp.max)||lp.min<1||lp.max<lp.min) refuse("invalid launcher protocol range");
      if (!Array.isArray(p.artifacts)||p.artifacts.length===0) refuse("invalid artifact set");
      const ids=p.artifacts.map((a,index)=>{
        if (!exact(a,["arch","format","name","os","sha256","size","url"])||typeof a.os!=="string"||typeof a.arch!=="string") refuse(`platform artifact ${index} has an unexpected shape`);
        const id=`${a.os}-${a.arch}`;
        const target=targets.find((t)=>t.os===a.os&&t.arch===a.arch);
        if (!target) refuse(`platform artifact ${id} is not a supported target`);
        if (a.format!==target.format) refuse(`platform artifact ${id} format must be ${target.format}`);
        const name=`station-server-${id}.${target.format}`;
        if (a.name!==name) refuse(`platform artifact ${id} name must be ${name}`);
        if (!plainUrl(a.url)) refuse(`platform artifact ${id} url is not a canonical HTTPS URL`,5);
        if (typeof a.sha256!=="string"||!/^[a-f0-9]{64}$/.test(a.sha256)) refuse(`platform artifact ${id} sha256 is invalid`);
        if (!Number.isSafeInteger(a.size)||a.size<=0) refuse(`platform artifact ${id} size is invalid`);
        return id;
      });
      const seen=new Set();
      for (const id of ids) { if (seen.has(id)) refuse(`duplicate platform artifact ${id}`); seen.add(id); }
      for (let index=1;index<p.artifacts.length;index+=1) {
        const previous=p.artifacts[index-1],current=p.artifacts[index];
        if (previous.os>current.os||(previous.os===current.os&&previous.arch>current.arch)) refuse("platform artifacts are not sorted by os, then arch");
      }
    };
    try {
      let envelope;
      try { envelope=JSON.parse(fs.readFileSync(manifestFile,"utf8")); } catch { refuse("manifest is not JSON"); }
      if (!exact(envelope,["algorithm","keyId","payload","schemaVersion","signature"])||envelope.schemaVersion!==1||envelope.algorithm!=="ed25519"||typeof envelope.keyId!=="string"||!/^[a-z0-9][a-z0-9-]{0,63}$/.test(envelope.keyId)||typeof envelope.signature!=="string"||!/^[A-Za-z0-9+/]+={0,2}$/.test(envelope.signature)) refuse("manifest envelope has an unexpected shape");
      const pinned=JSON.parse(pinnedKeysJson).keys.find((k)=>k.keyId===envelope.keyId&&k.algorithm==="ed25519");
      if (!pinned) refuse(`manifest signing key ${envelope.keyId} is not pinned`,2);
      const p=envelope.payload;
      if (typeof p?.channel!=="string") refuse("invalid manifest channel");
      if (!pinned.channels.includes(p.channel)) refuse(`signing key ${envelope.keyId} is not authorized for channel ${p.channel}`,3);
      const key=crypto.createPublicKey(testKeyFile?fs.readFileSync(testKeyFile,"utf8"):pinned.publicKeySpkiPem);
      if (!crypto.verify(null,Buffer.from(canonical(p)),key,Buffer.from(envelope.signature,"base64"))) refuse("manifest signature did not verify",4);
      if (!isObject(p)) refuse("manifest payload has an unexpected shape");
      if (p.schemaVersion===1) verifyV1(p);
      else if (p.schemaVersion===2) verifyV2(p);
      else refuse("unsupported manifest schema");
      if (p.channel!==expectedChannel) refuse(`manifest channel ${p.channel} does not match the expected channel ${expectedChannel}`,8);
      Object.assign(values,{channel:p.channel,releaseTag:p.releaseTag,version:p.version,sourceSha:p.sourceSha});
      process.stdout.write(`Verified the signed release manifest for Station ${p.releaseTag} (${p.channel}).\n`);
      if (p.schemaVersion===2) {
        const artifact=p.artifacts.find((a)=>`${a.os}-${a.arch}`===hostTarget);
        if (!artifact) refuse(`the release manifest has no server archive for ${hostTarget}`,6);
        const protocol=Number(launcherProtocolText);
        if (protocol<p.launcherProtocol.min||protocol>p.launcherProtocol.max) refuse(`${p.releaseTag} supports launcher protocols ${p.launcherProtocol.min}-${p.launcherProtocol.max}; this installer writes protocol ${protocol}`,7);
        Object.assign(values,{kind:"archive",url:artifact.url,sha256:artifact.sha256,size:String(artifact.size),name:artifact.name,format:artifact.format,nodeVersion:p.nodeVersion});
      }
    } catch (error) {
      process.stderr.write(`Station manifest verification: ${error instanceof Error ? error.message : String(error)}\n`);
      process.exit(error instanceof Refusal ? error.code : 1);
    }
    fs.mkdirSync(valuesDir,{mode:0o700});
    for (const [name,value] of Object.entries(values))
      fs.writeFileSync(path.join(valuesDir,name),value,{flag:"wx",mode:0o600});
  ' "$manifest_file" "$PINNED_MANIFEST_SIGNING_KEYS" "$test_key_file" "$manifest_values" "$RELEASE_RINGS_JSON" "$PORTABLE_SERVER_TARGETS_JSON" "$manifest_host_target" "$runtime_release_channel" "$INSTALLER_LAUNCHER_PROTOCOL" || {
    manifest_status=$?
    case "$manifest_status" in
      2) fail 'public ecosystem manifest is signed by a key this installer does not pin' ;;
      3) fail 'public ecosystem manifest signing key is not authorized for the manifest channel' ;;
      4) fail 'public ecosystem manifest signature did not verify' ;;
      5) fail 'public ecosystem manifest artifact URL is not in canonical form' ;;
      6) fail "public ecosystem manifest publishes no server archive for this host ($manifest_host_target)" ;;
      7) fail 'the release needs a newer installer: its launcher protocol is not one this installer writes' ;;
      # The signed channel must equal the requested one, and an unset
      # STATION_CHANNEL requests stable. Otherwise a manifest host could
      # answer a default `curl | sh` with a (validly signed) preview manifest
      # and install the beta runtime in its place.
      8) fail 'requested channel does not match public ecosystem manifest' ;;
      *) fail 'public ecosystem manifest is invalid' ;;
    esac
  }
  release_kind="$(cat "$manifest_values/kind")"
  release_channel="$(cat "$manifest_values/channel")"
  release_tag="$(cat "$manifest_values/releaseTag")"
  release_version="$(cat "$manifest_values/version")"
  release_sha="$(cat "$manifest_values/sourceSha")"
  asset_url="$(cat "$manifest_values/url")"
  expected_checksum="$(cat "$manifest_values/sha256")"
  [ "$version" = latest ] || [ "$version" = "$release_tag" ] || fail 'requested version does not match public ecosystem manifest'
  [ "$release_channel" = "$runtime_release_channel" ] || \
    fail 'requested channel does not match public ecosystem manifest'
  if [ "$release_kind" = archive ]; then
    archive_name="$(cat "$manifest_values/name")"
    archive_size="$(cat "$manifest_values/size")"
    archive_node_version="$(cat "$manifest_values/nodeVersion")"
    [ "$(cat "$manifest_values/format")" = tar.gz ] || \
      fail "$archive_name is not a tar.gz archive; this installer extracts tar.gz only"
  else
    require_source_toolchain
    archive_name="$ASSET_NAME"
  fi
  archive="$tmp_root/$archive_name"
  checksum_file="$tmp_root/$archive_name.sha256"
  if [ "$release_kind" = archive ]; then
    # The signed size bounds the download itself where curl can enforce it:
    # curl 8.4.0 and newer stop any transfer at one byte past it (exit 63);
    # older curl (Ubuntu 22.04's 7.81, Debian 12's 7.88) only refuses a
    # response whose Content-Length exceeds it, so a chunked response is
    # unbounded there. The size and sha256 checks below refuse it either way.
    curl -fsSL --retry 3 --retry-connrefused --connect-timeout 10 --max-filesize "$archive_size" -o "$archive" -- "$asset_url" || {
      download_status=$?
      [ "$download_status" != 63 ] || \
        fail "$archive_name is larger than the $archive_size bytes the signed manifest says"
      fail "could not download $archive_name"
    }
  else
    curl -fsSL --retry 3 --retry-connrefused --connect-timeout 10 -o "$archive" -- "$asset_url" || fail "could not download $archive_name"
  fi
  if [ "$release_kind" = archive ]; then
    downloaded_size="$(wc -c <"$archive" | tr -d ' ')"
    [ "$downloaded_size" = "$archive_size" ] || \
      fail "$archive_name is $downloaded_size bytes; the signed manifest says $archive_size"
  fi
  printf '%s  %s\n' "$expected_checksum" "$archive_name" > "$checksum_file"
else
  # The authenticated GitHub-release path serves source releases only.
  release_kind=source
  [ -n "${GH_TOKEN:-${GITHUB_TOKEN:-}}" ] || \
    fail 'GH_TOKEN or GITHUB_TOKEN is required; use the documented authenticated bootstrap command'
  gh auth status --hostname github.com >/dev/null 2>&1 || fail 'authenticated GitHub CLI access is required for signed releases'
  gh attestation verify --help >/dev/null 2>&1 || fail 'GitHub CLI attestation verification support is required'

if [ "$version" = latest ]; then
  release_metadata="$(gh api "repos/$REPOSITORY/releases?per_page=100")" || fail 'could not resolve signed GitHub releases'
  release_metadata="$(printf '%s' "$release_metadata" | node -e '
    const fs = require("node:fs"); const channel = process.argv[1]; const releases = JSON.parse(fs.readFileSync(0,"utf8"));
    const stable = /^v(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)$/;
    const preview = /^v(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)-preview\.([1-9]\d*)$/;
    const candidates = releases.filter((r) => !r?.draft && typeof r.tag_name === "string" && (channel === "stable" ? !r.prerelease && stable.test(r.tag_name) : r.prerelease && preview.test(r.tag_name)));
    if (!candidates.length) process.exit(1);
    const parts = (tag) => tag.match(/\d+/g).map(Number);
    candidates.sort((a,b) => { const ap=parts(a.tag_name), bp=parts(b.tag_name); for(let i=0;i<4;i++){const d=(bp[i]||0)-(ap[i]||0);if(d)return d;} return 0; });
    process.stdout.write(JSON.stringify(candidates[0]));
  ' "$release_channel")" || fail "no published $release_channel release is available"
else
  release_metadata="$(gh api "repos/$REPOSITORY/releases/tags/$version")" || fail "could not resolve release $version"
fi

release_tag="$(printf '%s' "$release_metadata" | node -e 'const fs=require("node:fs");const v=JSON.parse(fs.readFileSync(0,"utf8"));if(typeof v.tag_name!=="string"||typeof v.target_commitish!=="string")process.exit(1);process.stdout.write(v.tag_name)')" || fail 'release metadata is incomplete'
release_object="$(gh api "repos/$REPOSITORY/git/ref/tags/$release_tag")" || fail "could not resolve immutable source SHA for $release_tag"
release_object_type="$(printf '%s' "$release_object" | node -e 'const fs=require("node:fs");const v=JSON.parse(fs.readFileSync(0,"utf8"));if(!["commit","tag"].includes(v?.object?.type)||typeof v.object.sha!=="string")process.exit(1);process.stdout.write(v.object.type)')" || fail 'release tag ref is malformed'
release_sha="$(printf '%s' "$release_object" | node -e 'const fs=require("node:fs");const v=JSON.parse(fs.readFileSync(0,"utf8"));process.stdout.write(v.object.sha)')"
if [ "$release_object_type" = tag ]; then
  annotated_tag="$(gh api "repos/$REPOSITORY/git/tags/$release_sha")" || fail "could not peel annotated tag $release_tag"
  release_sha="$(printf '%s' "$annotated_tag" | node -e '
    const fs=require("node:fs");const v=JSON.parse(fs.readFileSync(0,"utf8"));
    if (v?.object?.type !== "commit" || typeof v.object.sha !== "string") process.exit(1);
    process.stdout.write(v.object.sha);
  ')" || fail "annotated tag $release_tag does not resolve directly to a commit"
fi
case "$release_sha" in *[!0-9a-fA-F]*|'') fail 'release source SHA is malformed' ;; esac
[ "${#release_sha}" = 40 ] || fail 'release source SHA must be full length'
case "$release_tag" in
  v[0-9]*-preview.[1-9]*) actual_channel=preview ;;
  v[0-9]*.*.*) actual_channel=stable ;;
  *) fail 'release tag does not match a supported ring' ;;
esac
[ "$actual_channel" = "$release_channel" ] || fail 'requested channel does not match the selected release tag'
printf '%s' "$release_metadata" | node -e '
  const fs=require("node:fs"); const [channel, tag]=process.argv.slice(1); const v=JSON.parse(fs.readFileSync(0,"utf8"));
  if (v.draft || v.tag_name !== tag || Boolean(v.prerelease) !== (channel === "preview")) process.exit(1);
' "$release_channel" "$release_tag" || fail 'release metadata channel/prerelease policy is invalid'

resolve_asset_url() {
  printf '%s' "$release_metadata" | node -e '
    const fs=require("node:fs"); const name=process.argv[1]; const v=JSON.parse(fs.readFileSync(0,"utf8"));
    const asset=Array.isArray(v.assets) ? v.assets.find((x)=>x?.name===name) : null;
    if (!asset || typeof asset.url!=="string" || !asset.url.startsWith("https://api.github.com/repos/kontourai/station/releases/assets/")) process.exit(1);
    process.stdout.write(asset.url);
  ' "$1"
}
ring_manifest_name="station-release-ring-$release_channel.json"
manifest_url="${STATION_INSTALL_MANIFEST_URL:-$(resolve_asset_url "$ring_manifest_name")}" || fail "release is missing $ring_manifest_name"
asset_url="${STATION_INSTALL_ASSET_URL:-$(resolve_asset_url "$ASSET_NAME")}" || fail "release is missing $ASSET_NAME"
checksum_url="${STATION_INSTALL_CHECKSUM_URL:-$(resolve_asset_url "$CHECKSUM_NAME")}" || fail "release is missing $CHECKSUM_NAME"
download_release_file() {
  url="$1" destination="$2"
  case "$url" in https://api.github.com/repos/$REPOSITORY/releases/assets/*) gh api -H 'Accept: application/octet-stream' "$url" >"$destination" ;; *) curl -fsSL --retry 3 --retry-connrefused --connect-timeout 10 -o "$destination" -- "$url" ;; esac
}
verify_attestation() {
  artifact="$1"
  gh attestation verify "$artifact" --repo "$REPOSITORY" --signer-workflow "$REPOSITORY/.github/workflows/release.yml" --source-ref "refs/tags/$release_tag" --source-digest "$release_sha" --cert-oidc-issuer 'https://token.actions.githubusercontent.com' --deny-self-hosted-runners || fail "attestation verification failed for $(basename "$artifact")"
}
manifest_file="$tmp_root/$ring_manifest_name"
download_release_file "$manifest_url" "$manifest_file" || fail "could not download $ring_manifest_name"
verify_attestation "$manifest_file"
manifest_values="$(node -e '
  const fs=require("node:fs");const [p,channel,tag,sha]=process.argv.slice(1);const v=JSON.parse(fs.readFileSync(p,"utf8"));
  const keys=Object.keys(v);const expected=["schemaVersion","channel","prerelease","ref","sha","createdAt","archive","checksum"];
  if (JSON.stringify(keys)!==JSON.stringify(expected)||v.schemaVersion!==1||v.channel!==channel||v.prerelease!==(channel==="preview")||v.ref!==tag||v.sha!==sha||typeof v.createdAt!=="string"||new Date(v.createdAt).toISOString()!==v.createdAt||v.archive?.name!=="station-portable.tar.gz"||! /^[0-9a-f]{64}$/i.test(v.archive?.sha256)||v.checksum?.name!=="station-portable.tar.gz.sha256"||! /^[0-9a-f]{64}$/i.test(v.checksum?.sha256))process.exit(1);process.stdout.write(`${v.archive.sha256}\n${v.checksum.sha256}`);
' "$manifest_file" "$release_channel" "$release_tag" "$release_sha")" || fail 'signed release-ring manifest is malformed or does not match the selected release'
archive_manifest_digest="$(printf '%s\n' "$manifest_values" | sed -n '1p')"
checksum_manifest_digest="$(printf '%s\n' "$manifest_values" | sed -n '2p')"
archive="$tmp_root/$ASSET_NAME" checksum_file="$tmp_root/$CHECKSUM_NAME"
download_release_file "$checksum_url" "$checksum_file" || fail "could not download $CHECKSUM_NAME"
verify_attestation "$checksum_file"
download_release_file "$asset_url" "$archive" || fail "could not download $ASSET_NAME"
verify_attestation "$archive"
# The verifier token and configured gh path are permitted only while resolving,
# downloading, and verifying immutable artifacts. Signed Station code executes
# as the current user; this prevents normal credential inheritance, not access
# to other user-readable files and is not an OS sandbox.
unset GH_TOKEN GITHUB_TOKEN
rm -rf "$gh_config_dir"
mkdir -m 000 "$gh_config_dir"
file_digest() { node -e 'const fs=require("node:fs"),c=require("node:crypto");process.stdout.write(c.createHash("sha256").update(fs.readFileSync(process.argv[1])).digest("hex"))' "$1"; }
[ "$(file_digest "$checksum_file")" = "$checksum_manifest_digest" ] || fail 'checksum bytes do not match signed manifest'
[ "$(file_digest "$archive")" = "$archive_manifest_digest" ] || fail 'archive bytes do not match signed manifest'

fi

expected_checksum="$(awk 'NR == 1 { print $1 }' "$checksum_file")"
case "$expected_checksum" in
  ''|*[!0-9A-Fa-f]*) fail 'release checksum is malformed' ;;
esac
[ "${#expected_checksum}" = 64 ] || fail 'release checksum must be SHA-256'

actual_checksum="$(sha256_of "$archive")"
[ "$actual_checksum" = "$expected_checksum" ] || fail 'release checksum did not match'

tar -tvzf "$archive" | awk '
  {
    type = substr($0, 1, 1)
    if (type != "-" && type != "d") exit 1
  }
' || fail 'release archive contains an unsupported entry type'

tar -tzf "$archive" | awk '
  BEGIN { valid = 1; count = 0 }
  {
    count += 1
    if ($0 !~ /^station\// || $0 ~ /(^|\/)\.\.?(\/|$)/) valid = 0
  }
  END { if (count == 0 || valid == 0) exit 1 }
' || fail 'release archive contains an unsafe path'

if [ "$release_kind" = archive ]; then
  # A prebuilt archive is several hundred megabytes unpacked, so it is
  # extracted once, straight into the install root, after the root is claimed
  # below. Its marker and provenance are read from the verified archive now,
  # before anything on disk changes.
  candidate="$tmp_root/archive-identity"
  mkdir -m 700 "$candidate"
  tar -xzf "$archive" -C "$candidate" --strip-components=1 \
    "station/.station-release.json" "station/$PREBUILT_ARCHIVE_MARKER" 2>/dev/null || \
    fail 'release archive is not a prebuilt Station archive (it has no marker or provenance)'
  [ -f "$candidate/$PREBUILT_ARCHIVE_MARKER" ] && [ ! -L "$candidate/$PREBUILT_ARCHIVE_MARKER" ] && \
    [ "$(cat "$candidate/$PREBUILT_ARCHIVE_MARKER")" = "$PREBUILT_ARCHIVE_SIGNATURE" ] && \
    [ "$(wc -c <"$candidate/$PREBUILT_ARCHIVE_MARKER" | tr -d ' ')" = "$((${#PREBUILT_ARCHIVE_SIGNATURE} + 1))" ] || \
    fail 'release archive marker is invalid'
else
extract_root="$tmp_root/extract"
mkdir -p "$extract_root"
tar -xzf "$archive" -C "$extract_root"
candidate="$extract_root/station"
[ -x "$candidate/station" ] || fail 'release archive is missing the Station launcher'
# Select the dependency contract from the verified archive, not this installer's
# revision. Older signed releases still own an npm-based lifecycle runner.
[ -f "$candidate/package.json" ] || fail 'release archive is missing package.json'
dependency_contract="$(node -e '
  const fs = require("node:fs");
  try {
    const manifest = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    if (!manifest || typeof manifest !== "object" || Array.isArray(manifest))
      throw new Error("release package.json must be an object");
    let manager = manifest.packageManager;
    const engineManager = manifest.devEngines?.packageManager;
    if (engineManager !== undefined) {
      if (!engineManager || typeof engineManager !== "object" ||
          typeof engineManager.name !== "string" || typeof engineManager.version !== "string")
        throw new Error("release has invalid package-manager metadata");
      const enginePin = `${engineManager.name}@${engineManager.version}`;
      if (manager !== undefined && manager !== enginePin)
        throw new Error("release has conflicting package-manager declarations");
      manager = enginePin;
    }
    if (typeof manifest.scripts?.["dependencies:ci"] !== "string" ||
        !manifest.scripts["dependencies:ci"].trim())
      throw new Error("release is missing its managed dependencies:ci runner");
    if (manager === undefined || (typeof manager === "string" && /^npm@[0-9]+\.[0-9]+\.[0-9]+$/.test(manager))) {
      process.stdout.write("npm");
    } else if (typeof manager === "string" && /^pnpm@11\.[0-9]+\.[0-9]+$/.test(manager)) {
      process.stdout.write("pnpm");
    } else {
      throw new Error("release packageManager must pin supported pnpm 11 or legacy npm");
    }
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
' "$candidate/package.json")" || fail 'release archive has unsupported dependency metadata'
case "$dependency_contract" in
  pnpm)
    [ -f "$candidate/pnpm-lock.yaml" ] || fail 'release archive is missing pnpm-lock.yaml'
    [ -f "$candidate/pnpm-workspace.yaml" ] || fail 'release archive is missing pnpm-workspace.yaml'
    [ ! -e "$candidate/package-lock.json" ] || fail 'release archive has ambiguous dependency lockfiles'
    ;;
  npm)
    [ -f "$candidate/package-lock.json" ] || fail 'legacy release archive is missing package-lock.json'
    [ ! -e "$candidate/pnpm-lock.yaml" ] && [ ! -e "$candidate/pnpm-workspace.yaml" ] ||
      fail 'legacy release archive has undeclared pnpm dependency configuration'
    ;;
  *) fail 'release archive has unsupported dependency metadata' ;;
esac
fi
[ -f "$candidate/.station-release.json" ] || fail 'release archive is missing provenance'
candidate_identity="$(node -e '
  const fs = require("node:fs");
  const [path, sha, ref, releaseChannel, ringsJson] = process.argv.slice(1);
  const value = JSON.parse(fs.readFileSync(path, "utf8"));
  const rings = JSON.parse(ringsJson);
  const ring = typeof value?.releaseChannel === "string" && Object.hasOwn(rings, value.releaseChannel)
    ? rings[value.releaseChannel] : undefined;
  let runtimeChannel;
  let provenanceReleaseChannel;
  if (value?.schemaVersion === 2 && ring &&
      value.channel === ring.runtimeChannel &&
      value.prerelease === ring.prerelease) {
    runtimeChannel = value.channel;
    provenanceReleaseChannel = value.releaseChannel;
  }
  if (!runtimeChannel || value.sha !== sha || value.ref !== ref ||
      provenanceReleaseChannel !== releaseChannel ||
      typeof value.createdAt !== "string" ||
      new Date(value.createdAt).toISOString() !== value.createdAt) {
    process.exit(1);
  }
  process.stdout.write(`${runtimeChannel}\n${provenanceReleaseChannel}`);
' "$candidate/.station-release.json" "$release_sha" "$release_tag" "$release_channel" "$RELEASE_RINGS_JSON")" || fail 'release provenance is invalid'

# The release ring is authenticated above. Only now translate its public
# stable/preview/nightly protocol into the local runtime's stable/beta/nightly
# identity and its exact, concurrent-safe roots.
runtime_channel="$(printf '%s\n' "$candidate_identity" | sed -n '1p')"
candidate_release_channel="$(printf '%s\n' "$candidate_identity" | sed -n '2p')"
[ "$candidate_release_channel" = "$release_channel" ] || fail 'release provenance channel does not match the verified release'
[ "$runtime_channel" = "$requested_runtime_channel" ] || \
  fail 'verified release does not match the requested runtime channel'
configure_runtime_paths "$runtime_channel"
normalize_runtime_paths
resolve_runtime_flags
assert_safe_remove_target "$install_root"
assert_roots_do_not_overlap
assert_install_root_is_channel_leaf
if [ -e "$state_file" ] || [ -L "$state_file" ]; then
  expected_install_root="$(canonicalize_path "$install_root")"
  expected_station_root="$(canonicalize_path "$station_root")"
  expected_station_home="$(canonicalize_path "$station_home")"
  recorded_ports="$(node -e '
    const fs = require("node:fs");
    const [p, runtimeChannel, releaseChannel, installRoot, stationRoot, stationHome, ringsJson] = process.argv.slice(1);
    const s = fs.lstatSync(p);
    if (!s.isFile() || s.isSymbolicLink() || (typeof process.getuid === "function" && s.uid !== process.getuid()) || (s.mode & 0o077) !== 0) process.exit(1);
    const v = JSON.parse(fs.readFileSync(p, "utf8"));
    const rings = JSON.parse(ringsJson);
    // Schema 4 adds the public manifest URL (null for the authenticated
    // GitHub-release path) so a packaged `station upgrade` needs no
    // environment; schema 3 installs are upgraded in place.
    if (![3, 4].includes(v?.schemaVersion) || (v.schemaVersion === 4 && v.manifestUrl !== null && typeof v.manifestUrl !== "string") || typeof v.releaseChannel !== "string" || !Object.hasOwn(rings, v.releaseChannel) || v.channel !== rings[v.releaseChannel].runtimeChannel || typeof v.installRoot !== "string" || typeof v.stationHome !== "string" || typeof v.stationRoot !== "string") process.exit(1);
    const savedRuntime = v.channel;
    const savedRelease = v.releaseChannel;
    if (savedRuntime !== runtimeChannel || savedRelease !== releaseChannel || (v.installRoot && v.installRoot !== installRoot) || (v.stationRoot && v.stationRoot !== stationRoot) || (v.stationHome && v.stationHome !== stationHome)) process.exit(3);
    // The ports the install ran on; recorded together, or not at all by
    // installers before #2675 slice C.
    const port = (value) => Number.isInteger(value) && value >= 1 && value <= 65535;
    if (v.serverPort === undefined && v.uiPort === undefined) process.exit(0);
    if (!port(v.serverPort) || !port(v.uiPort)) process.exit(1);
    process.stdout.write(`${v.serverPort} ${v.uiPort}`);
  ' "$state_file" "$runtime_channel" "$release_channel" "$expected_install_root" "$expected_station_root" "$expected_station_home" "$RELEASE_RINGS_JSON")" || {
    state_status=$?
    if [ "$state_status" = 3 ]; then
      fail 'existing install state does not match this verified channel root; remove the explicit root override or reinstall into a new scoped root'
    fi
    fail 'existing install channel state is unsafe or malformed'
  }
  if [ -n "$recorded_ports" ]; then
    recorded_server_port="${recorded_ports% *}"
    recorded_ui_port="${recorded_ports#* }"
    resolve_runtime_flags
  fi
fi

# Downgrade protection for the public-manifest path (archive#187). A signed
# manifest proves who published a release, not that it is newer than what is
# running: replaying an older, still-valid manifest must not roll an install
# back silently. The installed version is read from current/.station-release.json,
# which was verified at install time but is re-read here and is writable by this
# user: the check defends against a hostile manifest host replaying old releases,
# not against a local actor running as this user (who can already rewrite it).
#   newer manifest            -> install
#   same version, same bytes  -> nothing to do (exit 0, no restart)
#   same version, new bytes   -> refuse without the explicit opt-in below:
#                                a replayed, superseded archive of the same
#                                version is indistinguishable from a republish
#   older manifest            -> refuse without the explicit opt-in below
# The opt-in is the caller naming the exact version (STATION_VERSION=v<x.y.z>)
# AND setting STATION_INSTALL_ALLOW_ROLLBACK=1. One flag covers both cases on
# purpose: each replaces the running release with one the caller did not get
# by moving forward, so each needs the same deliberate "I want exactly this".
# The authenticated gh path is unchanged: there, STATION_VERSION already
# selects an exact signed release.
explicit_replacement_requested() {
  [ "${STATION_INSTALL_ALLOW_ROLLBACK:-0}" = 1 ] && [ "$version" = "$release_tag" ]
}
check_public_manifest_version() {
  [ -L "$current_link" ] || return 0
  version_order="$(node -e '
    const fs = require("node:fs");
    const [provenancePath, candidateTag, ringsJson] = process.argv.slice(1);
    const rings = JSON.parse(ringsJson);
    const parse = (tag) => {
      const match = /^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-([a-z]+)\.([1-9][0-9]*))?$/.exec(tag);
      if (!match || (match[4] !== undefined && !(Object.hasOwn(rings, match[4]) && rings[match[4]].prerelease))) return null;
      return { core: match.slice(1, 4).map(Number), label: match[4] ?? null, build: match[5] ? Number(match[5]) : null };
    };
    let installedTag;
    try { installedTag = JSON.parse(fs.readFileSync(provenancePath, "utf8"))?.ref; } catch { process.exit(1); }
    const installed = typeof installedTag === "string" ? parse(installedTag) : null;
    const candidate = parse(candidateTag);
    if (!installed || !candidate) process.exit(1);
    let order = 0;
    for (let index = 0; index < 3 && order === 0; index += 1)
      order = Math.sign(candidate.core[index] - installed.core[index]);
    if (order === 0) {
      if (installed.label === null && candidate.label === null) order = 0;
      else if (installed.label === null) order = -1;
      else if (candidate.label === null) order = 1;
      else if (installed.label !== candidate.label) process.exit(1);
      else order = Math.sign(candidate.build - installed.build);
    }
    process.stdout.write(`${order < 0 ? "older" : order > 0 ? "newer" : "same"}\n${installedTag}`);
  ' "$current_link/.station-release.json" "$release_tag" "$RELEASE_RINGS_JSON")" || {
    # Unreadable or incomparable installed provenance: only an explicit,
    # exact replacement may proceed, since nothing can say it is not older.
    if explicit_replacement_requested; then
      printf 'Warning: cannot read the installed Station version; replacing it with %s as explicitly requested (STATION_INSTALL_ALLOW_ROLLBACK=1).\n' "$release_tag" >&2
      return 0
    fi
    fail "cannot compare the installed release with $release_tag; set STATION_VERSION=$release_tag and STATION_INSTALL_ALLOW_ROLLBACK=1 to replace it explicitly"
  }
  version_relation="$(printf '%s\n' "$version_order" | sed -n '1p')"
  installed_tag="$(printf '%s\n' "$version_order" | sed -n '2p')"
  case "$version_relation" in
    newer) ;;
    same)
      if [ "$(readlink "$current_link")" = "$release_dir" ] && \
        [ -f "$release_dir/.station-install-complete" ] && \
        [ "$(cat "$release_dir/.station-install-complete")" = "$actual_checksum" ]; then
        printf 'Station %s is already installed; nothing to do.\n' "$release_tag"
        exit 0
      fi
      # The same version in the other layout (a source release built on
      # this host, or a prebuilt archive) is a change of packaging, not a
      # republish of the same artifact: no bytes of it are installed to be
      # replaced. Accepted: a replayed old signed manifest can therefore swap
      # a source vX for a previously published archive vX without a flag;
      # both are legitimately signed vX.
      if [ "$(dirname -- "$(readlink "$current_link")")" != "$releases_dir" ]; then
        if [ "$release_kind" = archive ]; then
          printf 'Moving Station %s from its source release to the prebuilt archive of the same version.\n' "$release_tag"
        else
          printf 'Moving Station %s from its prebuilt archive to the source release of the same version.\n' "$release_tag"
        fi
      elif explicit_replacement_requested; then
        printf 'Replacing the installed Station %s with different bytes published as the same version (STATION_INSTALL_ALLOW_ROLLBACK=1).\n' "$release_tag"
      else
        fail "refusing to replace the installed Station $installed_tag with different bytes published as the same version; to replace it deliberately, set STATION_VERSION=$release_tag and STATION_INSTALL_ALLOW_ROLLBACK=1"
      fi
      ;;
    older)
      if explicit_replacement_requested; then
        printf 'Rolling back Station from %s to %s (STATION_INSTALL_ALLOW_ROLLBACK=1).\n' "$installed_tag" "$release_tag"
      else
        fail "refusing to downgrade Station from $installed_tag to $release_tag; to roll back deliberately, set STATION_VERSION=$release_tag and STATION_INSTALL_ALLOW_ROLLBACK=1"
      fi
      ;;
    *) fail 'could not compare release versions' ;;
  esac
}
# A source release is addressed by its archive digest, since it is built in
# place. A prebuilt archive is addressed by its signed version: the directory
# is final when extracted, and rendered into service units later (#2675).
if [ "$release_kind" = archive ]; then
  releases_dir="$install_root/versions"
  release_dir="$releases_dir/$release_version"
  release_entry=bin/station
else
  releases_dir="$install_root/releases"
  release_dir="$releases_dir/$actual_checksum"
  release_entry=station
fi
if [ -n "$public_manifest_url" ]; then
  check_public_manifest_version
fi
prepare_owned_root "$install_root" "$INSTALL_ROOT_MARKER" "$INSTALL_ROOT_SIGNATURE" reject >/dev/null || \
  fail "STATION_INSTALL_ROOT is not an empty or installer-owned directory: $install_root"
data_root_state="$(prepare_owned_root "$station_home" "$DATA_ROOT_MARKER" "$DATA_ROOT_SIGNATURE" preserve)" || \
  fail "STATION_HOME is not a safe Station data directory: $station_home"
if [ "$data_root_state" = preserved ]; then
  printf 'Using existing Station data without claiming purge ownership: %s\n' "$station_home"
fi
prepare_safe_directory "$releases_dir"
prepare_safe_directory "$bin_dir"
assert_launcher_safe
previous_release=""
if [ -L "$current_link" ]; then
  previous_release="$(readlink "$current_link")"
fi

# Unquoted on purpose: two port words, or none.
archive_services="$(list_archive_services $(explicit_port_arguments))" || \
  fail "cannot switch this install around the Station services in $station_home/service (see above); nothing was changed"
if [ -n "$archive_services" ]; then
  [ "$release_kind" = archive ] || \
    fail "Station service(s) $archive_services run this install's prebuilt archive, which a source release cannot replace; uninstall them first (station service uninstall --instance=<name>)"
  for service_id in $archive_services; do
    service_state="$(service_unit_state "$service_id")" || \
      fail "could not determine whether Station service $service_id is running; nothing was changed (inspect it with: station service status --instance=$service_id --base=$station_home)"
    if [ "$service_state" = active ]; then
      active_services="${active_services:+$active_services }$service_id"
    fi
  done
fi

release_complete=false
if [ -d "$release_dir" ] && [ ! -L "$release_dir" ] && \
  [ -x "$release_dir/$release_entry" ] && \
  [ -f "$release_dir/.station-install-complete" ] && \
  [ "$(cat "$release_dir/.station-install-complete")" = "$actual_checksum" ]; then
  release_complete=true
fi

# Set when an explicitly requested replacement (same version, new bytes) of
# the ACTIVE archive version must move it aside; see publish_release below.
displaced_release=""
replace_active_version=false

# Verifies an extracted prebuilt archive: the archive's own launcher reports
# the release identity and the Node.js that actually runs it, which must be
# the signed manifest's. Then the completion sentinel. The tree is sealed
# read-only (seal_archive_version) only once it has its final name, because
# some filesystems refuse to rename a read-only directory.
finish_archive_version() {
  version_dir="$1"
  version_report="$tmp_root/version-report.json"
  if ! (cd / && "$version_dir/bin/station" --version --json) >"$version_report"; then
    return 1
  fi
  node -e '
    const fs = require("node:fs");
    const [report, tag, sha, runtimeChannel, releaseChannel, nodeVersion] = process.argv.slice(1);
    let value;
    try { value = JSON.parse(fs.readFileSync(report, "utf8")); } catch { process.exit(1); }
    if (value?.ref !== tag || value.sha !== sha || value.channel !== runtimeChannel ||
        value.releaseChannel !== releaseChannel || value.node !== `v${nodeVersion}`) process.exit(1);
  ' "$version_report" "$release_tag" "$release_sha" "$runtime_channel" "$release_channel" "$archive_node_version" || \
    return 1
  printf '%s\n' "$actual_checksum" >"$version_dir/.station-install-complete"
}

# An installed archive version is immutable, and lifecycle state lives
# outside it (#2675 B1).
seal_archive_version() {
  chmod -R a-w "$1"
}

if [ "$release_complete" = false ] && [ "$release_kind" = archive ]; then
  if [ -e "$release_dir" ] || [ -L "$release_dir" ]; then
    if [ "$previous_release" = "$release_dir" ]; then
      # Only an explicit, exact replacement reaches here with the active
      # version (check_public_manifest_version refuses anything else). It is
      # moved aside only after Station stops.
      [ -f "$release_dir/.station-install-complete" ] || \
        fail 'the active release cache is incomplete; refusing to replace running files'
      replace_active_version=true
    else
      safe_remove_tree "$release_dir"
    fi
  fi
  printf 'Extracting Station %s...\n' "$release_tag"
  release_stage="$releases_dir/.stage.$$"
  incoming_release="$releases_dir/.incoming.$$"
  for leftover in "$release_stage" "$incoming_release"; do
    if [ -e "$leftover" ] || [ -L "$leftover" ]; then
      safe_remove_tree "$leftover"
    fi
  done
  mkdir -m 700 "$release_stage"
  if ! tar -xzf "$archive" -C "$release_stage"; then
    safe_remove_tree "$release_stage"
    fail 'could not extract the release archive'
  fi
  node -e 'require("node:fs").renameSync(process.argv[1], process.argv[2])' \
    "$release_stage/station" "$incoming_release"
  rmdir "$release_stage"
  # The files extracted are the ones whose identity was read above.
  if ! cmp -s "$candidate/.station-release.json" "$incoming_release/.station-release.json" || \
    ! cmp -s "$candidate/$PREBUILT_ARCHIVE_MARKER" "$incoming_release/$PREBUILT_ARCHIVE_MARKER"; then
    safe_remove_tree "$incoming_release"
    fail 'the extracted release does not match the verified archive'
  fi
  if ! finish_archive_version "$incoming_release"; then
    safe_remove_tree "$incoming_release"
    fail "the extracted release did not report itself as Station $release_tag on Node.js $archive_node_version"
  fi
  if [ "$replace_active_version" = false ]; then
    if ! node -e 'require("node:fs").renameSync(process.argv[1], process.argv[2])' \
      "$incoming_release" "$release_dir" || ! seal_archive_version "$release_dir"; then
      safe_remove_tree "$incoming_release"
      safe_remove_tree "$release_dir"
      fail 'could not place the verified release'
    fi
  fi
elif [ "$release_complete" = false ]; then
  if [ -e "$release_dir" ] || [ -L "$release_dir" ]; then
    [ "$previous_release" != "$release_dir" ] || \
      fail 'the active release cache is incomplete; refusing to replace running files'
    safe_remove_tree "$release_dir"
  fi
  printf 'Installing Station dependencies...\n'
  (cd "$candidate" && HOME="$build_home" GH_CONFIG_DIR="$gh_config_dir" npm run dependencies:ci)
  release_stage="$install_root/releases/.stage.$$"
  if [ -e "$release_stage" ] || [ -L "$release_stage" ]; then
    safe_remove_tree "$release_stage"
  fi
  mv "$candidate" "$release_stage"
  node -e '
    const fs = require("node:fs");
    fs.renameSync(process.argv[1], process.argv[2]);
  ' "$release_stage" "$release_dir"
  # Build in the directory the release runs from (#2703). Without --instance,
  # the lifecycle names a build after its code root, home, and ports, so a
  # build made in the extraction candidate was named after a directory that no
  # longer exists and the first start rebuilt with the user's real HOME.
  # Until the completion marker below is written this release is incomplete,
  # and the next install replaces it.
  printf 'Building Station...\n'
  if ! (cd "$release_dir" && \
    HOME="$build_home" GH_CONFIG_DIR="$gh_config_dir" \
    STATION_CHANNEL="$runtime_channel" STATION_ROOT="$station_root" STATION_HOME="$station_home" \
    ./station build --base="$station_home" \
      "--port=$resolved_server_port" "--ui-port=$resolved_ui_port"); then
    safe_remove_tree "$release_dir"
    fail 'the release build failed'
  fi
  printf '%s\n' "$actual_checksum" >"$release_dir/.station-install-complete"
else
  printf 'Station release already installed; reusing verified files.\n'
fi

canonical_install_root="$(canonicalize_path "$install_root")"
canonical_station_root="$(canonicalize_path "$station_root")"
canonical_station_home="$(canonicalize_path "$station_home")"
if [ -f "$state_file" ]; then
  node -e '
    const fs = require("node:fs");
    fs.copyFileSync(process.argv[1], process.argv[2], fs.constants.COPYFILE_EXCL);
    fs.chmodSync(process.argv[2], 0o600);
  ' "$state_file" "$previous_state_backup" || fail 'could not preserve previous install channel state'
fi
if [ -e "$launcher" ] || [ -L "$launcher" ]; then
  node -e '
      const fs = require("node:fs");
      fs.copyFileSync(process.argv[1], process.argv[2], fs.constants.COPYFILE_EXCL);
      fs.chmodSync(process.argv[2], 0o755);
    ' "$launcher" "$previous_launcher_backup" || fail 'could not preserve the previous channel launcher'
  previous_launcher_present=true
fi
write_staged_launcher
state_stage="$install_root/.station-release-state.$$"
umask 077
# Schema 4 records the public manifest URL this install came from, so a
# packaged `station upgrade` re-runs the same verified path without the
# caller's environment (#2675). The authenticated GitHub-release path has no
# manifest URL and keeps writing schema 3, which released CLIs and installers
# (they accept schema 3 only) can still read. Both record the ports this run
# resolved (those Station was started on, or would be under
# STATION_INSTALL_NO_START=1), so an upgrade that does not name ports keeps
# them; readers ignore fields they do not know.
node -e '
  const fs = require("node:fs");
  const [path, channel, releaseChannel, installRoot, stationRoot, stationHome, manifestUrl, server, ui] = process.argv.slice(1);
  const ports = { serverPort: Number(server), uiPort: Number(ui) };
  const state = manifestUrl
    ? { schemaVersion: 4, channel, releaseChannel, installRoot, stationRoot, stationHome, manifestUrl, ...ports }
    : { schemaVersion: 3, channel, releaseChannel, installRoot, stationRoot, stationHome, ...ports };
  if (!Object.values(ports).every((port) => Number.isInteger(port) && port >= 1 && port <= 65535)) process.exit(1);
  fs.writeFileSync(path, `${JSON.stringify(state)}\n`, { mode: 0o600, flag: "wx" });
  const fd = fs.openSync(path, "r");
  try { fs.fsyncSync(fd); } finally { fs.closeSync(fd); }
' "$state_stage" "$runtime_channel" "$release_channel" "$canonical_install_root" "$canonical_station_root" "$canonical_station_home" "$public_manifest_url" "$resolved_server_port" "$resolved_ui_port" || fail 'could not stage install channel state'

if [ "$replace_active_version" = true ]; then
  # Same version, new bytes, explicitly requested: the running version is
  # moved aside (it stays the rollback target) and the verified one takes its
  # name. current already names that path.
  stop_for_switch
  moving_aside="$releases_dir/$release_version.replaced.$$"
  # Station is stopped: a failure here restarts the untouched version.
  move_version_dir "$release_dir" "$moving_aside" || \
    fail_with_rollback 'could not move the running release aside'
  displaced_release="$moving_aside"
  previous_release="$displaced_release"
  if ! node -e 'require("node:fs").renameSync(process.argv[1], process.argv[2])' "$incoming_release" "$release_dir" || \
    ! seal_archive_version "$release_dir" || \
    ! replace_link_atomically "$release_dir" "$current_link" || \
    ! node -e 'require("node:fs").renameSync(process.argv[1], process.argv[2])' "$staged_launcher" "$launcher"; then
    fail_with_rollback 'could not publish the new release'
  fi
elif [ "$previous_release" != "$release_dir" ]; then
  stop_for_switch
  if ! replace_link_atomically "$release_dir" "$current_link" || \
    ! node -e 'require("node:fs").renameSync(process.argv[1], process.argv[2])' "$staged_launcher" "$launcher"; then
    fail_with_rollback 'could not publish the new release'
  fi
else
  # A reused release may still be running from the previous install; the
  # later start must not race that live instance for its own ports. Every
  # failure after this stop rolls back so the previously-running Station is
  # never left stopped (the "previous" release here is the same release, so
  # rollback is a restart, not a downgrade).
  stop_for_switch
  node -e 'require("node:fs").renameSync(process.argv[1], process.argv[2])' "$staged_launcher" "$launcher" || \
    fail_with_rollback 'could not publish the channel launcher'
fi

node -e 'require("node:fs").renameSync(process.argv[1], process.argv[2])' "$state_stage" "$state_file" || \
  fail_with_rollback 'could not persist install channel state'
state_stage=""

if [ "${STATION_INSTALL_NO_START:-0}" != 1 ]; then
  if [ -n "$active_services" ]; then
    # The unit runs `current`, which now names the new release. A service
    # that does not come back as that release, answering its identity
    # probes, puts the previous release back and restarts it (identity
    # rollback; the supervisor-owned trial replaces this in slice D).
    for service_id in $active_services; do
      printf 'Restarting Station service %s...\n' "$service_id"
      if ! run_service_command start "$service_id" >/dev/null || \
        ! service_runs_release "$service_id"; then
        fail_with_rollback "Station service $service_id did not come back as $release_tag"
      fi
    done
  elif ! start_installed_station; then
    fail_with_rollback 'the new release did not start'
  fi
  # Keep the active release and the one it replaced (the rollback target),
  # in either layout, and remove every other one, including stages a crashed
  # install left behind. (A supervisor's pending version arrives with #2675
  # slice D; until then nothing else is pending.)
  for installed_release in "$install_root"/releases/* "$install_root"/versions/* \
    "$install_root"/versions/.stage.* "$install_root"/versions/.incoming.*; do
    [ -d "$installed_release" ] && [ ! -L "$installed_release" ] || continue
    if [ "$installed_release" != "$release_dir" ] && \
      [ "$installed_release" != "$previous_release" ]; then
      safe_remove_tree "$installed_release"
    fi
  done
fi

printf '\nStation is installed at %s\n' "$current_link"
printf 'Launcher: %s\n' "$launcher"
case ":$PATH:" in
  *":$bin_dir:"*) ;;
  *) printf 'Add %s to PATH to run station from any directory.\n' "$bin_dir" ;;
esac
if [ "${STATION_INSTALL_NO_START:-0}" = 1 ] && [ -n "$active_services" ]; then
  for service_id in $active_services; do
    printf 'Station service %s was stopped for the switch; start it with: %s service start --instance=%s\n' "$service_id" "$launcher" "$service_id"
  done
elif [ "${STATION_INSTALL_NO_START:-0}" = 1 ]; then
  printf 'Start it with: %s start\n' "$launcher"
elif [ -n "$active_services" ]; then
  # Each unit serves the ports it was installed with, not necessarily these.
  for service_id in $active_services; do
    printf 'Station service %s is running %s; see it with: %s service status --instance=%s\n' "$service_id" "$release_tag" "$launcher" "$service_id"
  done
else
  printf 'Open http://localhost:%s\n' "$resolved_ui_port"
fi
