import { type ChildProcessWithoutNullStreams, spawn } from 'node:child_process';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { createServer } from 'node:net';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test } from '@playwright/test';

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = join(dirname(__filename), '..');
const CLI_ENTRY = join(REPO_ROOT, 'packages/cli/src/cli.ts');
const TSX_CLI = join(REPO_ROOT, 'node_modules/tsx/dist/cli.mjs');
const ORIGINAL_COPY =
  'This scaffold is ready for you to replace with real UI, queries, and plugin-specific actions.';

function findFreePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = createServer();
    server.unref();
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      if (!address || typeof address === 'string') {
        server.close(() => reject(new Error('Failed to allocate a port')));
        return;
      }
      server.close(() => resolve(address.port));
    });
  });
}

function stationCliArgs(args: string[]): string[] {
  return [TSX_CLI, CLI_ENTRY, ...args];
}

function runStationCommand({
  args,
  cwd,
  env,
}: {
  args: string[];
  cwd: string;
  env: NodeJS.ProcessEnv;
}): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, stationCliArgs(args), {
      cwd,
      env,
      windowsHide: true,
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk) => {
      stdout += chunk;
    });
    child.stderr.on('data', (chunk) => {
      stderr += chunk;
    });
    child.on('error', reject);
    child.on('exit', (code) => {
      if (code === 0) {
        resolve({ stdout, stderr });
        return;
      }
      reject(
        new Error(
          `station ${args.join(' ')} exited with ${code}\n${stdout}\n${stderr}`,
        ),
      );
    });
  });
}

function startStationCommand({
  args,
  cwd,
  env,
}: {
  args: string[];
  cwd: string;
  env: NodeJS.ProcessEnv;
}): { child: ChildProcessWithoutNullStreams; output: () => string } {
  const child = spawn(process.execPath, stationCliArgs(args), {
    cwd,
    env,
    windowsHide: true,
  });
  let output = '';
  child.stdout.on('data', (chunk) => {
    output += chunk;
  });
  child.stderr.on('data', (chunk) => {
    output += chunk;
  });
  return { child, output: () => output };
}

async function stopProcess(child: ChildProcessWithoutNullStreams) {
  if (child.exitCode !== null || child.killed) {
    return;
  }

  child.kill('SIGTERM');
  const exited = await Promise.race([
    new Promise<boolean>((resolve) => child.once('exit', () => resolve(true))),
    new Promise<boolean>((resolve) => setTimeout(() => resolve(false), 5000)),
  ]);

  if (!exited && child.exitCode === null) {
    child.kill('SIGKILL');
  }
}

async function fetchText(url: string): Promise<string> {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      return '';
    }
    return response.text();
  } catch {
    return '';
  }
}

test.describe('plugin dev hot reload', () => {
  test('serves and hot reloads a plugin generated by station plugin create', async ({
    page,
  }) => {
    test.setTimeout(180_000);

    const root = await mkdtemp(join(tmpdir(), 'station-plugin-dev-'));
    const pluginName = 'hot-reload-proof';
    const pluginDir = join(root, pluginName);
    const port = await findFreePort();
    const env = {
      ...process.env,
      STATION_HOME: join(root, '.station-home'),
      npm_config_cache: join(root, '.npm-cache'),
    };
    let dev: ReturnType<typeof startStationCommand> | null = null;

    try {
      const createResult = await runStationCommand({
        args: ['plugin', 'create', pluginName, '--template=layout'],
        cwd: root,
        env,
      });
      expect(createResult.stdout).toContain(
        `Created layout plugin: ${pluginName}/`,
      );

      dev = startStationCommand({
        args: ['plugin', 'dev', String(port), '--no-mcp'],
        cwd: pluginDir,
        env,
      });

      const origin = `http://127.0.0.1:${port}`;
      await expect
        .poll(
          async () => {
            if (dev?.child.exitCode !== null) {
              return `exit:${dev?.child.exitCode}\n${dev?.output()}`;
            }
            const html = await fetchText(origin);
            return html.includes('Hot Reload Proof — Dev Preview')
              ? 'ready'
              : 'waiting';
          },
          { timeout: 120_000 },
        )
        .toBe('ready');

      await expect
        .poll(() => dev?.output() || '', { timeout: 10_000 })
        .toContain(`Plugin: Hot Reload Proof`);
      await expect(await fetchText(`${origin}/react-dev.js`)).toContain(
        'window.React',
      );
      await expect(await fetchText(`${origin}/sdk-dev.js`)).toContain(
        'window.__station_sdk',
      );

      await page.goto(`${origin}/#/layout/${pluginName}`);
      await expect(
        page.getByRole('heading', { name: 'Hot Reload Proof' }),
      ).toBeVisible();
      await expect(page.getByText(ORIGINAL_COPY)).toBeVisible();

      const updatedCopy = `Browser hot reload proof ${Date.now()}`;
      const entryPath = join(pluginDir, 'src/index.tsx');
      const source = await readFile(entryPath, 'utf8');
      await writeFile(entryPath, source.replace(ORIGINAL_COPY, updatedCopy));

      await expect
        .poll(() => dev?.output() || '', { timeout: 60_000 })
        .toContain('changed — rebuilding');
      await expect(page.getByText(updatedCopy)).toBeVisible({
        timeout: 60_000,
      });
    } finally {
      if (dev) {
        await stopProcess(dev.child);
      }
      await rm(root, { recursive: true, force: true });
    }
  });
});
