import { AsyncLocalStorage } from 'node:async_hooks';
import { createHash, randomUUID } from 'node:crypto';
import { join } from 'node:path';
import {
  DEPLOYMENT_AUTHENTICATION_VERSION,
  type DeploymentAuthenticationHost,
  type DeploymentAuthenticationProvider,
  type DeploymentAuthenticationResult,
  type PendingEnrollmentSessionResult,
} from '@kontourai/station-contracts/deployment-authentication';
import { type BetterAuthOptions, betterAuth } from 'better-auth';
import {
  addOAuthServerContext,
  createAuthMiddleware,
  getOAuthState,
} from 'better-auth/api';
import { getCookies } from 'better-auth/cookies';
import { getMigrations } from 'better-auth/db/migration';
import { genericOAuth, username } from 'better-auth/plugins';
import { z } from 'zod/v3';
import {
  awaitSettlementWithin,
  raceWithSignal,
} from '../../utils/bounded-async.js';
import { openPrivateSqlite } from '../../utils/private-sqlite.js';
import { LocalAccountAdministration } from './local-account-administration.js';
import {
  createOidcAccountSubject,
  type LocalAccountOidcProvider,
} from './local-account-oidc.js';

export interface LocalAccountEmail {
  kind: 'verify-email' | 'reset-password';
  recipient: string;
  url: string;
}

export interface LocalAccountEnrollment {
  /** Checks the real pending invitation. This is eligibility to register, never membership. */
  mayRegister(input: { invitation: string; email?: string }): Promise<boolean>;
  /** Server-owned mail transport; callers must not supply a delivery destination. */
  deliver(message: LocalAccountEmail): Promise<void>;
}

export interface LocalAccountProvider extends DeploymentAuthenticationProvider {
  /** Private operator route composition only; never forwarded through provider.handle. */
  administration: LocalAccountAdministration;
  issueRecovery(accountId: string): Promise<string>;
}

interface PendingEnrollmentAttemptState {
  readonly enrollmentId: string;
  retired: boolean;
  creating: boolean;
  createdSession: boolean;
  readonly creations: Set<Promise<unknown>>;
  readonly signIns: Set<Promise<unknown>>;
  cleanupAll: boolean;
  cleanupRequested: boolean;
  readonly cleanupSessionIds: Set<string>;
}

interface LocalAccountProviderTestHooks {
  /**
   * Test-only barrier at the real session-create hook boundary. Production
   * composition never supplies it; the Better Auth database insert is shared.
   */
  beforePendingSessionCreate?: (enrollmentId: string) => Promise<void>;
}

const PENDING_ENROLLMENT_SETTLEMENT_TIMEOUT_MS = 10_000;
const MAX_PENDING_ENROLLMENT_ATTEMPTS = 4096;

/** Maintained password/session implementation behind Station's common authentication contract. */
export async function createLocalAccountProvider(
  host: Readonly<DeploymentAuthenticationHost>,
  secret: string,
  enrollment: LocalAccountEnrollment,
  mode: 'email-password' | 'username-password' = 'email-password',
  oidc: readonly LocalAccountOidcProvider[] = [],
  testHooks: LocalAccountProviderTestHooks = {},
): Promise<LocalAccountProvider> {
  if (secret.length < 32)
    throw new Error(
      'Local accounts require an operator-owned authentication secret.',
    );
  const databasePath = join(host.stateDirectory, 'local-accounts.sqlite');
  const localUsername = mode === 'username-password';
  const database = openPrivateSqlite(databasePath, 'Local accounts');
  const recoveries = new Map<string, (url: string) => void>();
  const pendingEnrollmentScope =
    new AsyncLocalStorage<PendingEnrollmentAttemptState>();
  const pendingAttempts = new Map<string, PendingEnrollmentAttemptState>();
  let closed = false;
  try {
    function pendingAttempt(
      enrollmentId: string,
    ): PendingEnrollmentAttemptState | undefined {
      let attempt = pendingAttempts.get(enrollmentId);
      if (!attempt) {
        // IDs are generated by trusted Station code and remain tombstoned until
        // restart so a completed/retired attempt cannot be replayed. Bound the
        // retained set; fail closed at capacity rather than evicting IDs.
        if (pendingAttempts.size >= MAX_PENDING_ENROLLMENT_ATTEMPTS)
          return undefined;
        attempt = {
          enrollmentId,
          retired: false,
          creating: false,
          createdSession: false,
          creations: new Set(),
          signIns: new Set(),
          cleanupAll: false,
          cleanupRequested: false,
          cleanupSessionIds: new Set(),
        };
        pendingAttempts.set(enrollmentId, attempt);
      }
      return attempt;
    }

    function cleanupRetiredAttempt(
      attempt: PendingEnrollmentAttemptState,
    ): boolean {
      if (!attempt.cleanupRequested) return true;
      if (!localUsername || closed) return false;
      try {
        if (attempt.cleanupAll) {
          database
            .prepare('DELETE FROM session WHERE stationPendingEnrollmentId = ?')
            .run(attempt.enrollmentId);
        } else {
          for (const sessionId of attempt.cleanupSessionIds) {
            database
              .prepare(
                `DELETE FROM session WHERE id = ?
                 AND stationPendingEnrollmentId = ?`,
              )
              .run(sessionId, attempt.enrollmentId);
          }
        }
        const remaining = database
          .prepare(
            'SELECT COUNT(*) AS count FROM session WHERE stationPendingEnrollmentId = ?',
          )
          .get(attempt.enrollmentId)?.count;
        return Number(remaining) === 0;
      } catch {
        // A closed database is swept on the next provider open. This callback
        // is deliberately independent of the request that may already abort.
        return false;
      }
    }

    function retirePendingAttempt(
      attempt: PendingEnrollmentAttemptState,
      sessionId?: string,
    ): boolean {
      attempt.retired = true;
      attempt.cleanupRequested = true;
      if (sessionId) attempt.cleanupSessionIds.add(sessionId);
      else attempt.cleanupAll = true;
      return cleanupRetiredAttempt(attempt);
    }

    function trackAttemptOperation<T>(
      attempt: PendingEnrollmentAttemptState,
      set: Set<Promise<unknown>>,
      operation: Promise<T>,
    ): Promise<T> {
      set.add(operation);
      const settle = () => {
        set.delete(operation);
        cleanupRetiredAttempt(attempt);
      };
      void operation.then(settle, settle);
      return operation;
    }

    async function waitForAttemptSettlement(
      attempt: PendingEnrollmentAttemptState,
      signal: AbortSignal,
    ): Promise<boolean> {
      const work = Promise.allSettled([
        ...attempt.creations,
        ...attempt.signIns,
      ]);
      let settled: boolean;
      try {
        settled = await raceWithSignal(
          awaitSettlementWithin(work, PENDING_ENROLLMENT_SETTLEMENT_TIMEOUT_MS),
          signal,
        );
      } catch {
        return false;
      }
      return settled && !attempt.creations.size && !attempt.signIns.size;
    }

    const administration = new LocalAccountAdministration(
      database,
      localUsername,
    );
    const options = {
      database,
      secret,
      baseURL: host.publicOrigin,
      basePath: host.basePath,
      trustedOrigins: [...(host.allowedBrowserOrigins ?? [host.publicOrigin])],
      telemetry: { enabled: false },
      logger: { disabled: true },
      emailAndPassword: {
        enabled: true,
        requireEmailVerification: !localUsername,
        autoSignIn: false,
        minPasswordLength: 12,
        maxPasswordLength: 128,
        revokeSessionsOnPasswordReset: true,
        resetPasswordTokenExpiresIn: 20 * 60,
        sendResetPassword: async ({ user, token }) => {
          const url = `${host.publicOrigin}/account/reset#token=${encodeURIComponent(token)}`;
          if (localUsername) {
            const accept = recoveries.get(user.email);
            if (!accept)
              throw new Error(
                'Local account recovery requires operator authorization.',
              );
            accept(url);
            return;
          }
          await enrollment.deliver({
            kind: 'reset-password',
            recipient: user.email,
            // The account recovery view submits the token explicitly; GET or
            // mail-preview navigation never consumes it. Fragments stay off HTTP logs.
            url,
          });
        },
      },
      emailVerification: {
        sendOnSignUp: !localUsername,
        sendOnSignIn: !localUsername,
        autoSignInAfterVerification: false,
        sendVerificationEmail: async ({ user, url }) =>
          enrollment.deliver({
            kind: 'verify-email',
            recipient: user.email,
            url,
          }),
      },
      session: {
        expiresIn: 60 * 60 * 24,
        deferSessionRefresh: true,
        cookieCache: { enabled: false },
        ...(localUsername
          ? {
              additionalFields: {
                stationPendingEnrollmentId: {
                  type: 'string',
                  required: false,
                  input: false,
                  returned: false,
                },
              },
            }
          : {}),
      },
      advanced: {
        cookiePrefix: `station-account-${createHash('sha256').update(host.stationId).digest('hex').slice(0, 20)}`,
        useSecureCookies: host.publicOrigin.startsWith('https:'),
      },
      account: { accountLinking: { enabled: false }, encryptOAuthTokens: true },
      plugins: [
        ...(localUsername
          ? [
              username({
                minUsernameLength: 3,
                maxUsernameLength: 32,
                usernameValidator: (value) =>
                  /^[a-zA-Z0-9][a-zA-Z0-9_.-]{2,31}$/.test(value),
              }),
            ]
          : []),
        ...(oidc.length
          ? [
              genericOAuth({
                config: oidc.map((provider) => ({
                  providerId: provider.id,
                  name: provider.displayName,
                  discoveryUrl: `${provider.issuer.replace(/\/$/, '')}/.well-known/openid-configuration`,
                  clientId: provider.clientId,
                  clientSecret: provider.clientSecret,
                  scopes: ['openid', 'profile', 'email'],
                  pkce: true,
                  requireIdTokenVerification: true,
                  accountSubject: createOidcAccountSubject(provider),
                  disableImplicitSignUp: true,
                  disableProviderLogout: true,
                })),
              }),
            ]
          : []),
      ],
      hooks: {
        before: createAuthMiddleware(async (context) => {
          if (context.path !== '/sign-in/social') return;
          const invitation = context.request?.headers.get(
            'x-station-invitation',
          );
          if (invitation)
            await addOAuthServerContext({ stationInvitation: invitation });
        }),
      },
      rateLimit: { enabled: true, storage: 'database', window: 60, max: 10 },
      user: {
        additionalFields: {
          verifiedAt: { type: 'date', required: false, input: false },
        },
      },
      databaseHooks: {
        session: {
          create: {
            before: async (session) => {
              if (!administration.permits(session.userId)) return false;
              const attempt = pendingEnrollmentScope.getStore();
              if (!attempt) return undefined;
              if (attempt.retired) return false;
              await testHooks.beforePendingSessionCreate?.(
                attempt.enrollmentId,
              );
              if (attempt.retired) return false;
              return {
                data: {
                  stationPendingEnrollmentId: attempt.enrollmentId,
                },
              };
            },
          },
        },
        user: {
          create: {
            before: async (user, context) => {
              const oauthState = await getOAuthState();
              const callbackInvitation =
                oauthState?.serverContext?.stationInvitation;
              const invitation =
                typeof callbackInvitation === 'string'
                  ? callbackInvitation
                  : context?.request?.headers.get('x-station-invitation');
              const eligible =
                !!invitation &&
                (await enrollment.mayRegister({
                  invitation,
                  ...(!localUsername || (oauthState && user.emailVerified)
                    ? { email: user.email }
                    : {}),
                }));
              if (!eligible) return false;
              return user.emailVerified === true
                ? { data: { ...user, verifiedAt: new Date() } }
                : true;
            },
          },
          update: {
            before: async (user) =>
              user.emailVerified === true
                ? { data: { ...user, verifiedAt: new Date() } }
                : undefined,
          },
        },
      },
    } satisfies BetterAuthOptions;
    const migration = await getMigrations(options);
    await migration.runMigrations();
    if (localUsername) {
      // An unpromoted enrollment is tied to an in-memory pairing attempt. A
      // process restart retires every such attempt before the provider opens.
      database
        .prepare(
          'DELETE FROM session WHERE stationPendingEnrollmentId IS NOT NULL',
        )
        .run();
    }
    const auth = betterAuth(options);
    const context = await auth.$context;
    const availableOidc = new Set(
      oidc
        .filter((configured) => {
          const provider = context.socialProviders.find(
            (entry) => entry.id === configured.id,
          );
          return (
            provider?.issuer === configured.issuer &&
            !!provider.idToken &&
            !!provider.requiresIdTokenNonce
          );
        })
        .map((provider) => provider.id),
    );

    function resolveSession(
      current: {
        user: {
          id: string;
          name: string;
          email: string;
          emailVerified: boolean;
          verifiedAt?: unknown;
        };
        session: { id: string; createdAt: Date; expiresAt: Date };
      } | null,
    ): DeploymentAuthenticationResult {
      if (
        !current ||
        (!localUsername &&
          (!current.user.emailVerified ||
            !(current.user.verifiedAt instanceof Date)))
      )
        return { kind: 'invalid', reason: 'invalid-credential' };
      if (current.session.expiresAt.getTime() <= Date.now())
        return { kind: 'invalid', reason: 'expired' };
      if (!administration.permits(current.user.id, current.session.createdAt))
        return { kind: 'invalid', reason: 'revoked' };
      return {
        kind: 'authenticated',
        session: {
          subject: current.user.id,
          displayName: current.user.name,
          sessionId: current.session.id,
          authenticatedAt: current.session.createdAt.toISOString(),
          expiresAt: current.session.expiresAt.toISOString(),
          contacts:
            current.user.emailVerified &&
            current.user.verifiedAt instanceof Date
              ? [
                  {
                    kind: 'email',
                    value: current.user.email,
                    verifiedAt: (current.user.verifiedAt as Date).toISOString(),
                  },
                ]
              : [],
        },
      };
    }

    function liveSessionRecord(
      sessionId: string,
    ): { token: string; enrollmentId?: string } | undefined {
      const row = localUsername
        ? database
            .prepare(
              `SELECT token, stationPendingEnrollmentId FROM session
               WHERE id = ?`,
            )
            .get(sessionId)
        : database
            .prepare('SELECT token FROM session WHERE id = ?')
            .get(sessionId);
      if (typeof row?.token !== 'string') return undefined;
      return {
        token: row.token,
        ...(typeof row.stationPendingEnrollmentId === 'string'
          ? { enrollmentId: row.stationPendingEnrollmentId }
          : {}),
      };
    }

    async function verifyPendingEnrollment(
      enrollmentId: string,
      sessionId: string,
      signal: AbortSignal,
    ): Promise<PendingEnrollmentSessionResult> {
      if (closed || signal.aborted) return { kind: 'unavailable' };
      const row = liveSessionRecord(sessionId);
      if (!row || !row.enrollmentId)
        return { kind: 'invalid', reason: 'revoked' };
      if (row.enrollmentId !== enrollmentId)
        return { kind: 'invalid', reason: 'conflicting-identity' };
      const context = await auth.$context;
      const current = await context.internalAdapter.findSession(row.token);
      if (closed || signal.aborted) return { kind: 'unavailable' };
      const latest = liveSessionRecord(sessionId);
      if (!latest || latest.token !== row.token)
        return { kind: 'invalid', reason: 'revoked' };
      if (latest.enrollmentId !== enrollmentId)
        return { kind: 'invalid', reason: 'conflicting-identity' };
      const resolved = resolveSession(current);
      if (resolved.kind === 'invalid' || resolved.kind === 'unavailable')
        return resolved;
      if (resolved.kind !== 'authenticated')
        return { kind: 'invalid', reason: 'revoked' };
      if (resolved.session.sessionId !== sessionId)
        return { kind: 'invalid', reason: 'conflicting-identity' };
      return {
        kind: 'pending',
        session: {
          enrollmentId,
          sessionId,
          subject: resolved.session.subject,
          displayName: resolved.session.displayName,
          expiresAt: resolved.session.expiresAt,
        },
      };
    }

    async function usernameLogin(
      request: Request,
    ): Promise<DeploymentAuthenticationResult>;
    async function usernameLogin(
      request: Request,
      attempt: PendingEnrollmentAttemptState,
    ): Promise<PendingEnrollmentSessionResult>;
    async function usernameLogin(
      request: Request,
      attempt?: PendingEnrollmentAttemptState,
    ): Promise<
      DeploymentAuthenticationResult | PendingEnrollmentSessionResult
    > {
      if (closed || request.signal.aborted) return { kind: 'unavailable' };
      const parsed = z
        .object({
          username: z.string().min(3).max(32),
          password: z.string().min(1).max(128),
        })
        .strict()
        .safeParse(
          await raceWithSignal(request.clone().json(), request.signal),
        );
      if (!parsed.success)
        return { kind: 'invalid', reason: 'invalid-credential' };
      if (closed || request.signal.aborted || attempt?.retired)
        return { kind: 'unavailable' };
      const signIn = () =>
        auth.api.signInUsername({
          body: parsed.data,
          headers: request.headers,
          asResponse: true,
        });
      if (closed || request.signal.aborted || attempt?.retired)
        return { kind: 'unavailable' };
      const signInOperation = attempt
        ? trackAttemptOperation(
            attempt,
            attempt.signIns,
            pendingEnrollmentScope.run(attempt, signIn),
          )
        : signIn();
      const response = await raceWithSignal(signInOperation, request.signal);
      if (closed || request.signal.aborted || attempt?.retired)
        return { kind: 'unavailable' };
      if (!response.ok)
        return { kind: 'invalid', reason: 'invalid-credential' };
      const credentials = response.headers
        .getSetCookie()
        .filter((value) => value.startsWith(`${cookie}=`))
        .map((value) => value.split(';')[0])
        .join('; ');
      const current = await auth.api.getSession({
        headers: new Headers({ Cookie: credentials }),
        query: { disableCookieCache: true, disableRefresh: true },
      });
      if (closed || request.signal.aborted) return { kind: 'unavailable' };
      if (attempt) {
        if (attempt.retired) return { kind: 'unavailable' };
        if (!current) return { kind: 'invalid', reason: 'revoked' };
        return verifyPendingEnrollment(
          attempt.enrollmentId,
          current.session.id,
          request.signal,
        );
      }
      return resolveSession(current);
    }

    const signUpPath = localUsername ? '/sign-up/username' : '/sign-up/email';
    const signInPath = localUsername ? '/sign-in/username' : '/sign-in/email';
    const endpoints: DeploymentAuthenticationProvider['endpoints'] = [
      ...oidc.flatMap((provider) => [
        {
          path: `/oidc/${provider.id}/begin`,
          methods: ['POST'] as const,
          operation: 'begin-login' as const,
        },
        {
          path: `/callback/${provider.id}`,
          methods: ['GET'] as const,
          operation: 'callback' as const,
        },
      ]),
      { path: signUpPath, methods: ['POST'], operation: 'register' },
      { path: signInPath, methods: ['POST'], operation: 'begin-login' },
      { path: '/sign-out', methods: ['POST'], operation: 'logout' },
      {
        path: '/send-verification-email',
        methods: ['POST'],
        operation: 'verify-contact',
      },
      { path: '/verify-email', methods: ['GET'], operation: 'verify-contact' },
      {
        path: '/request-password-reset',
        methods: ['POST'],
        operation: 'request-recovery',
      },
      {
        path: '/reset-password',
        methods: ['POST'],
        operation: 'complete-recovery',
      },
      {
        path: '/change-password',
        methods: ['POST'],
        operation: 'change-password',
      },
      { path: '/get-session', methods: ['POST'], operation: 'refresh-session' },
      {
        path: '/revoke-sessions',
        methods: ['POST'],
        operation: 'revoke-session',
      },
      {
        path: '/revoke-other-sessions',
        methods: ['POST'],
        operation: 'revoke-session',
      },
    ].filter(
      (endpoint) =>
        !localUsername ||
        !['verify-contact', 'request-recovery'].includes(endpoint.operation),
    ) as DeploymentAuthenticationProvider['endpoints'];
    const cookie = getCookies(options).sessionToken.name;
    return {
      administration,
      async issueRecovery(accountId) {
        if (!localUsername || closed || !administration.permits(accountId))
          throw new Error('Local account recovery is unavailable.');
        const row = database
          .prepare('SELECT email FROM user WHERE id = ?')
          .get(accountId);
        if (typeof row?.email !== 'string' || recoveries.has(row.email))
          throw new Error('Local account recovery is unavailable.');
        let url: string | undefined;
        recoveries.set(row.email, (value) => {
          url = value;
        });
        try {
          await auth.api.requestPasswordReset({ body: { email: row.email } });
          if (!url || !administration.permits(accountId))
            throw new Error('Local account recovery was not created.');
          return url;
        } finally {
          recoveries.delete(row.email);
        }
      },
      version: DEPLOYMENT_AUTHENTICATION_VERSION,
      issuer: `urn:station:local-accounts:${host.stationId}`,
      displayName: 'Station account',
      login: {
        kind: mode,
        signInPath,
        signUpPath,
      },
      ...(oidc.length
        ? {
            externalLogins: oidc.map((provider) => ({
              id: provider.id,
              displayName: provider.displayName,
              startPath: `/oidc/${provider.id}/begin`,
              available: availableOidc.has(provider.id),
            })),
          }
        : {}),
      sessionCookies: [cookie],
      endpoints,
      sessionReferences: {
        async revoke(sessionId, signal) {
          if (closed || signal.aborted)
            throw new Error('Account session is unavailable.');
          const row = database
            .prepare('SELECT token FROM session WHERE id = ?')
            .get(sessionId);
          if (typeof row?.token !== 'string') return;
          const context = await auth.$context;
          await context.internalAdapter.deleteSession(row.token);
        },
        async verify(sessionId, signal) {
          if (closed || signal.aborted) return { kind: 'unavailable' };
          // The pinned library owns session parsing and user joins. Its bearer
          // is looked up only inside this provider and never leaves the Station.
          const row = liveSessionRecord(sessionId);
          if (!row) return { kind: 'invalid', reason: 'revoked' };
          if (row.enrollmentId) return { kind: 'invalid', reason: 'revoked' };
          const context = await auth.$context;
          const current = await context.internalAdapter.findSession(row.token);
          if (closed || signal.aborted) return { kind: 'unavailable' };
          const latest = liveSessionRecord(sessionId);
          if (!latest || latest.token !== row.token)
            return { kind: 'invalid', reason: 'revoked' };
          if (latest.enrollmentId)
            return { kind: 'invalid', reason: 'revoked' };
          return resolveSession(current);
        },
        ...(localUsername
          ? {
              login(request: Request): Promise<DeploymentAuthenticationResult> {
                return usernameLogin(request);
              },
              pendingEnrollment: {
                async create(enrollmentId, request) {
                  if (
                    closed ||
                    request.signal.aborted ||
                    !/^[A-Za-z0-9._:-]{16,128}$/.test(enrollmentId)
                  )
                    return { kind: 'unavailable' };
                  const attempt = pendingAttempt(enrollmentId);
                  if (!attempt) return { kind: 'unavailable' };
                  if (
                    attempt.retired ||
                    attempt.creating ||
                    attempt.createdSession
                  )
                    return {
                      kind: 'invalid',
                      reason: 'conflicting-identity',
                    };
                  attempt.creating = true;
                  const operation = trackAttemptOperation(
                    attempt,
                    attempt.creations,
                    usernameLogin(request, attempt),
                  );
                  try {
                    const result = await operation;
                    if (result.kind === 'pending') {
                      attempt.createdSession = true;
                    } else if (
                      result.kind === 'invalid' &&
                      result.reason === 'invalid-credential'
                    ) {
                      retirePendingAttempt(attempt);
                      return result;
                    } else {
                      retirePendingAttempt(attempt);
                    }
                    return result;
                  } catch {
                    retirePendingAttempt(attempt);
                    return { kind: 'unavailable' };
                  } finally {
                    attempt.creating = false;
                  }
                },
                verify: verifyPendingEnrollment,
                async promote(enrollmentId, sessionId, signal) {
                  if (closed || signal.aborted)
                    throw new Error(
                      'Pending enrollment promotion is unavailable.',
                    );
                  const attempt = pendingAttempt(enrollmentId);
                  if (!attempt)
                    throw new Error(
                      'Pending enrollment promotion is unavailable.',
                    );
                  if (attempt.cleanupRequested)
                    throw new Error(
                      'Pending enrollment promotion is unavailable.',
                    );
                  attempt.retired = true;
                  const settled = await waitForAttemptSettlement(
                    attempt,
                    signal,
                  );
                  if (!settled || closed || signal.aborted)
                    throw new Error(
                      'Pending enrollment promotion is unconfirmed.',
                    );
                  const verified = await verifyPendingEnrollment(
                    enrollmentId,
                    sessionId,
                    signal,
                  );
                  if (verified.kind !== 'pending')
                    throw new Error(
                      'Pending enrollment promotion is unavailable.',
                    );
                  // This is the commit boundary. If cancellation arrives before
                  // this point, keep generic verification closed; once the
                  // conditional update succeeds, report the committed promotion.
                  if (closed || signal.aborted)
                    throw new Error(
                      'Pending enrollment promotion is unavailable.',
                    );
                  const changed = database
                    .prepare(
                      `UPDATE session SET stationPendingEnrollmentId = NULL
                       WHERE id = ? AND stationPendingEnrollmentId = ?`,
                    )
                    .run(sessionId, enrollmentId);
                  if (changed.changes !== 1)
                    throw new Error(
                      'Pending enrollment promotion is unavailable.',
                    );
                },
                async discard(enrollmentId, sessionId, signal) {
                  const attempt = pendingAttempt(enrollmentId);
                  if (!attempt) {
                    if (closed || signal.aborted)
                      throw new Error(
                        'Pending enrollment cleanup is unconfirmed.',
                      );
                    if (sessionId)
                      database
                        .prepare(
                          `DELETE FROM session WHERE id = ?
                           AND stationPendingEnrollmentId = ?`,
                        )
                        .run(sessionId, enrollmentId);
                    else
                      database
                        .prepare(
                          'DELETE FROM session WHERE stationPendingEnrollmentId = ?',
                        )
                        .run(enrollmentId);
                    const remaining = database
                      .prepare(
                        'SELECT COUNT(*) AS count FROM session WHERE stationPendingEnrollmentId = ?',
                      )
                      .get(enrollmentId)?.count;
                    if (Number(remaining) !== 0)
                      throw new Error(
                        'Pending enrollment cleanup is unconfirmed.',
                      );
                    return;
                  }
                  if (!retirePendingAttempt(attempt, sessionId))
                    throw new Error(
                      'Pending enrollment cleanup is unconfirmed.',
                    );
                  if (closed || signal.aborted)
                    throw new Error(
                      'Pending enrollment cleanup is unconfirmed.',
                    );
                  const settled = await waitForAttemptSettlement(
                    attempt,
                    signal,
                  );
                  if (!settled || closed)
                    throw new Error(
                      'Pending enrollment cleanup is unconfirmed.',
                    );
                  if (
                    !cleanupRetiredAttempt(attempt) ||
                    attempt.creations.size ||
                    attempt.signIns.size
                  )
                    throw new Error(
                      'Pending enrollment cleanup is unconfirmed.',
                    );
                  const remaining = database
                    .prepare(
                      'SELECT COUNT(*) AS count FROM session WHERE stationPendingEnrollmentId = ?',
                    )
                    .get(enrollmentId)?.count;
                  if (Number(remaining) !== 0)
                    throw new Error(
                      'Pending enrollment cleanup is unconfirmed.',
                    );
                },
              },
            }
          : {}),
      },
      async authenticate(request) {
        if (closed || request.signal.aborted) return { kind: 'unavailable' };
        const current = await auth.api.getSession({
          headers: request.headers,
          query: { disableCookieCache: true, disableRefresh: true },
        });
        if (closed || request.signal.aborted) return { kind: 'unavailable' };
        if (current && localUsername) {
          const latest = liveSessionRecord(current.session.id);
          if (!latest || latest.token !== current.session.token)
            return { kind: 'invalid', reason: 'revoked' };
          if (latest.enrollmentId)
            return { kind: 'invalid', reason: 'revoked' };
        }
        return resolveSession(current);
      },
      async handle(request) {
        const path = new URL(request.url).pathname.slice(host.basePath.length);
        if (
          !endpoints.some(
            (endpoint) =>
              endpoint.path === path &&
              endpoint.methods.some((method) => method === request.method),
          )
        ) {
          return Response.json(
            { error: { code: 'authentication_operation_unsupported' } },
            { status: 404 },
          );
        }
        let operation = request;
        const external = oidc.find(
          (provider) => path === `/oidc/${provider.id}/begin`,
        );
        if (external) {
          if (!availableOidc.has(external.id))
            return Response.json(
              { error: { code: 'oidc_provider_unavailable' } },
              { status: 503 },
            );
          const body = z
            .object({})
            .strict()
            .safeParse(await request.clone().json());
          const invitation = request.headers.get('x-station-invitation');
          if (
            !body.success ||
            (invitation && !/^[A-Za-z0-9._-]{16,2048}$/.test(invitation))
          )
            return Response.json(
              { error: { code: 'invalid_oidc_login' } },
              { status: 400 },
            );
          const headers = new Headers(request.headers);
          headers.delete('Content-Length');
          headers.set('Content-Type', 'application/json');
          const response = await auth.handler(
            new Request(`${host.publicOrigin}${host.basePath}/sign-in/social`, {
              method: 'POST',
              headers,
              signal: request.signal,
              body: JSON.stringify({
                provider: external.id,
                callbackURL: `${host.publicOrigin}/account`,
                errorCallbackURL: `${host.publicOrigin}/account`,
                requestSignUp: !!invitation,
                disableRedirect: true,
              }),
            }),
          );
          if (!response.ok)
            return Response.json(
              { error: { code: 'oidc_login_unavailable' } },
              { status: response.status },
            );
          const value: unknown = await response.json();
          const parsed = z.object({ url: z.string().url() }).safeParse(value);
          if (!parsed.success)
            return Response.json(
              { error: { code: 'oidc_login_unavailable' } },
              { status: 503 },
            );
          const destination = new URL(parsed.data.url);
          if (
            destination.protocol !== 'https:' &&
            !(
              destination.protocol === 'http:' &&
              ['localhost', '127.0.0.1', '[::1]'].includes(destination.hostname)
            )
          )
            return Response.json(
              { error: { code: 'oidc_login_unavailable' } },
              { status: 503 },
            );
          const outgoing = new Headers(response.headers);
          outgoing.delete('Content-Length');
          return new Response(
            JSON.stringify({ data: { url: parsed.data.url } }),
            { status: 200, headers: outgoing },
          );
        }
        if (path === signUpPath) {
          const input: unknown = await request.clone().json();
          const invitation = request.headers.get('x-station-invitation');
          const email =
            input &&
            typeof input === 'object' &&
            'email' in input &&
            typeof input.email === 'string'
              ? input.email.toLowerCase()
              : undefined;
          if (
            !invitation ||
            (!localUsername && !email) ||
            !(await enrollment.mayRegister({
              invitation,
              ...(localUsername ? {} : { email }),
            }))
          ) {
            return Response.json(
              { error: { code: 'invitation_required' } },
              { status: 403 },
            );
          }
          if (localUsername) {
            const parsed = z
              .object({
                username: z.string().regex(/^[a-zA-Z0-9][a-zA-Z0-9_.-]{2,31}$/),
                password: z.string().min(12).max(128),
                name: z.string().trim().min(1).max(128).optional(),
              })
              .strict()
              .safeParse(input);
            if (!parsed.success)
              return Response.json(
                { error: { code: 'invalid_request' } },
                { status: 400 },
              );
            const headers = new Headers(request.headers);
            headers.delete('Content-Length');
            operation = new Request(
              `${host.publicOrigin}${host.basePath}/sign-up/email`,
              {
                method: 'POST',
                headers,
                signal: request.signal,
                body: JSON.stringify({
                  ...parsed.data,
                  name: parsed.data.name ?? parsed.data.username,
                  // Better Auth requires a unique internal email column. This
                  // reserved-domain value is never contact or identity evidence.
                  email: `${randomUUID()}@station.invalid`,
                }),
              },
            );
          }
        }
        if (path === '/change-password') {
          const body: unknown = await request.clone().json();
          if (!body || typeof body !== 'object' || Array.isArray(body))
            return Response.json(
              { error: { code: 'invalid_request' } },
              { status: 400 },
            );
          const headers = new Headers(request.headers);
          headers.delete('Content-Length');
          operation = new Request(request.url, {
            method: request.method,
            headers,
            signal: request.signal,
            body: JSON.stringify({ ...body, revokeOtherSessions: true }),
          });
        }
        const callbackProvider = oidc.find(
          (provider) => path === `/callback/${provider.id}`,
        );
        if (callbackProvider && !availableOidc.has(callbackProvider.id))
          return Response.json(
            { error: { code: 'oidc_provider_unavailable' } },
            { status: 503 },
          );
        const response = await auth.handler(operation);
        if (
          response.ok &&
          [signInPath, signUpPath, '/get-session', '/change-password'].includes(
            path,
          )
        ) {
          // Session tokens stay in HttpOnly cookies. The core self endpoint
          // supplies the closed identity view without library token records.
          const headers = new Headers(response.headers);
          headers.delete('Content-Length');
          headers.set('Content-Type', 'application/json');
          return new Response(JSON.stringify({ success: true }), {
            status: response.status,
            headers,
          });
        }
        return response;
      },
      async close() {
        if (closed) return;
        closed = true;
        database.close();
      },
    };
  } catch (error) {
    database.close();
    throw error;
  }
}
