/**
 * The in-process guard Station preloads into the device hub (#1970, hub
 * lockdown, design amendment round 5).
 *
 * expo-device-hub and its vendored serve-sim/serve-emu servers have no
 * authentication: serve-sim's `/api` discloses an exec token and `/exec`
 * runs shell commands; `/api/devices/ws` streams the inventory to any
 * origin. A DNS-rebinding page, or any local process, could reach them.
 * Station owns the spawn, so it preloads this guard with
 * `NODE_OPTIONS=--require <guard>`. NODE_OPTIONS (not argv) is inherited by
 * every node process the hub starts, including serve-sim's DETACHED stream
 * helpers, so each of their servers is guarded too.
 *
 * What the guard does, in every guarded process:
 * - Patches `http.Server.prototype.emit` so a `request`, `upgrade` or
 *   `connect` without the per-launch secret header
 *   (`x-station-hub-secret`, from `STATION_HUB_GUARD_SECRET`) is answered
 *   403 and closed before the hub's own handler runs. Exec/shell paths are
 *   refused even with the secret.
 * - In the hub's own process (`expo-device-hub/dist/server/cli.mjs`), also
 *   admits only Station's path allowlist (`hubGuardAllowlist()`): the
 *   dashboard, `/vendor/serve-sim/api`, `/exec`, `/exec-ws`, WebRTC
 *   offers, devtools and device boot/create/remove are unreachable.
 * - Adds the secret header to the process's own loopback HTTP requests
 *   (`http.request`/`http.get`/`fetch`), so the hub can still reach the
 *   helpers it spawned.
 * - Refuses to spawn `prebuild-install`, so serve-emu's WebRTC path cannot
 *   download an unpinned native binary at runtime (WebRTC is unsupported).
 *
 * NODE_OPTIONS is inherited by every child, node or not; non-node children
 * (`xcrun`, `adb`, the emulator, native helpers) ignore it, and any node
 * child runs guarded. The guard patches only `http.Server`: serve-emu's
 * scrcpy `adb forward` ports and serve-sim's camera UNIX socket (in the
 * private TMPDIR) are not HTTP listeners it can see; they are disclosed in
 * `device-hub-helpers.ts`.
 *
 * NODE_OPTIONS is deliberately OVERWRITTEN, not appended to: the hub's
 * environment is an allowlist, so an operator's own NODE_OPTIONS (which
 * could preload other code into the hub) never reaches it.
 *
 * In expo-device-hub 0.10.1 the hub serves `stream.mjpeg` itself; serve-sim's
 * detached helper starts only from `GET /vendor/serve-sim/`, which the guard
 * refuses, so no Station path starts a helper. Guarding helpers (and killing
 * any that exist) is defence in depth.
 *
 * The secret sits in the hub's environment because its children must
 * inherit it; the threat is remote pages and other local processes, which
 * never see that environment. The guard's behaviour is verified against the
 * hub versions in {@link HUB_GUARD_VERIFIED_VERSIONS}; the supervisor
 * refuses to launch any other version.
 */
import { hubGuardAllowlist } from './device-hub-connection.js';

/** Hub versions whose route surface this guard was checked against. */
export const HUB_GUARD_VERIFIED_VERSIONS: readonly string[] = ['0.10.1'];

export const HUB_GUARD_SECRET_ENV = 'STATION_HUB_GUARD_SECRET';

/** The CommonJS source the supervisor writes and preloads. */
export function buildHubGuardSource(): string {
  const lists = JSON.stringify(hubGuardAllowlist());
  return `'use strict';
// Station device hub guard. Generated by Station; do not edit.
(() => {
  const http = require('node:http');
  const crypto = require('node:crypto');
  const childProcess = require('node:child_process');
  const Module = require('node:module');
  const HEADER = 'x-station-hub-secret';
  const SECRET = process.env[${JSON.stringify(HUB_GUARD_SECRET_ENV)}] || '';
  const LISTS = ${lists};
  const GET = LISTS.get.map((s) => new RegExp(s));
  const POST = LISTS.post.map((s) => new RegExp(s));
  const WS = LISTS.websocket.map((s) => new RegExp(s));
  const FORBIDDEN = new RegExp(LISTS.forbidden, 'i');
  const HUB_ROLE = /[\\\\/]expo-device-hub[\\\\/]dist[\\\\/]server[\\\\/]cli\\.mjs$/.test(
    process.argv[1] || '',
  );

  const secretOk = (req) => {
    const value = req.headers[HEADER];
    if (typeof value !== 'string' || SECRET.length < 32) return false;
    const a = Buffer.from(value);
    const b = Buffer.from(SECRET);
    return a.length === b.length && crypto.timingSafeEqual(a, b);
  };
  const pathOf = (req) => {
    const raw = typeof req.url === 'string' ? req.url : '';
    const at = raw.indexOf('?');
    return at === -1 ? raw : raw.slice(0, at);
  };
  const clean = (p) =>
    p.startsWith('/') &&
    !p.includes('%') &&
    !p.includes('\\\\') &&
    !p.includes('//') &&
    !p.split('/').some((s) => s === '.' || s === '..') &&
    !FORBIDDEN.test(p);
  const admitted = (kind, req) => {
    if (!secretOk(req)) return false;
    const p = pathOf(req);
    if (!clean(p)) return false;
    if (!HUB_ROLE) return true;
    if (kind === 'upgrade') return WS.some((re) => re.test(p));
    const method = String(req.method || '').toUpperCase();
    if (method === 'GET' || method === 'HEAD') return GET.some((re) => re.test(p));
    if (method === 'POST') return POST.some((re) => re.test(p));
    return false;
  };

  const emit = http.Server.prototype.emit;
  http.Server.prototype.emit = function guardedEmit(event, ...args) {
    if (event === 'request') {
      const [req, res] = args;
      if (!admitted('request', req)) {
        res.statusCode = 403;
        res.setHeader('Content-Type', 'text/plain; charset=utf-8');
        res.setHeader('Connection', 'close');
        res.end('Forbidden');
        return true;
      }
    } else if (event === 'upgrade' || event === 'connect') {
      const [req, socket] = args;
      if (event === 'connect' || !admitted('upgrade', req)) {
        try {
          socket.end('HTTP/1.1 403 Forbidden\\r\\nConnection: close\\r\\nContent-Length: 0\\r\\n\\r\\n');
        } catch {}
        socket.destroy();
        return true;
      }
    }
    return emit.call(this, event, ...args);
  };

  const loopback = (host) => {
    const h = String(host || '').replace(/^\\[|\\]$/g, '').toLowerCase();
    return h === '127.0.0.1' || h === 'localhost' || h === '::1';
  };
  const withSecret = (args) => {
    const out = [...args];
    const first = out[0];
    let host;
    let index;
    if (typeof first === 'string' || first instanceof URL) {
      try {
        host = new URL(String(first)).hostname;
      } catch {
        return out;
      }
      if (out[1] && typeof out[1] === 'object') index = 1;
      else {
        out.splice(1, 0, {});
        index = 1;
      }
    } else if (first && typeof first === 'object') {
      host = first.hostname || first.host || 'localhost';
      index = 0;
    } else return out;
    if (!loopback(host)) return out;
    const options = out[index];
    out[index] = { ...options, headers: { ...(options.headers || {}), [HEADER]: SECRET } };
    return out;
  };
  const request = http.request;
  http.request = function guardedRequest(...args) {
    return request.apply(this, withSecret(args));
  };
  http.get = function guardedGet(...args) {
    const req = http.request(...args);
    req.end();
    return req;
  };
  const originalFetch = globalThis.fetch;
  if (typeof originalFetch === 'function') {
    globalThis.fetch = function guardedFetch(input, init) {
      try {
        const href = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
        if (loopback(new URL(href).hostname)) {
          const headers = new Headers((init && init.headers) || (input instanceof Request ? input.headers : undefined));
          headers.set(HEADER, SECRET);
          init = { ...(init || {}), headers };
        }
      } catch {}
      return originalFetch.call(this, input, init);
    };
  }

  const mentionsPrebuild = (value) =>
    typeof value === 'string'
      ? /prebuild-install/.test(value)
      : Array.isArray(value) && value.some((item) => typeof item === 'string' && /prebuild-install/.test(item));
  const refusal = () =>
    new Error('Station hub guard: runtime native downloads (prebuild-install) are disabled.');
  const promisifyCustom = require('node:util').promisify.custom;
  for (const name of ['spawn', 'spawnSync', 'execFile', 'execFileSync', 'exec', 'execSync', 'fork']) {
    const original = childProcess[name];
    if (typeof original !== 'function') continue;
    const guarded = function guardedChildProcess(...args) {
      if (args.some(mentionsPrebuild)) throw refusal();
      return original.apply(this, args);
    };
    // Keep every own property of the original, above all
    // util.promisify.custom: without it promisify(execFile) resolves to a
    // bare string instead of {stdout, stderr}, and simctl/adb parsing in the
    // hub silently finds no devices. The custom form is guarded too.
    const descriptors = Object.getOwnPropertyDescriptors(original);
    delete descriptors[promisifyCustom];
    delete descriptors.prototype;
    Object.defineProperties(guarded, descriptors);
    const custom = original[promisifyCustom];
    if (typeof custom === 'function')
      Object.defineProperty(guarded, promisifyCustom, {
        configurable: true,
        value: function guardedPromisified(...args) {
          if (args.some(mentionsPrebuild)) return Promise.reject(refusal());
          return custom.apply(this, args);
        },
      });
    childProcess[name] = guarded;
  }
  Module.syncBuiltinESMExports();
})();
`;
}
