import { describe, expect, it } from 'vitest';
import {
  findPnpmLockProblems,
  pnpmPackageExtensionsChecksum,
} from '../lockfile-sync-gate.mjs';

describe('pnpm lock authority', () => {
  function inputs() {
    return {
      manifests: {
        '.': { dependencies: { consumer: '^1.0.0' } },
        'packages/widget': { dependencies: { consumer: '^2.0.0' } },
      },
      config: { overrides: { 'consumer>peer': '^3.0.0' } },
      lock: {
        importers: {
          '.': {
            dependencies: {
              consumer: { specifier: '^1.0.0', version: '1.0.0(peer@3.0.0)' },
            },
          },
          'packages/widget': {
            dependencies: {
              consumer: { specifier: '^2.0.0', version: '2.0.0(peer@3.0.0)' },
            },
          },
        },
        overrides: { 'consumer>peer': '^3.0.0' },
        packages: {
          'consumer@1.0.0': { peerDependencies: { peer: '^2.0.0' } },
          'consumer@2.0.0': { peerDependencies: { peer: '^3.0.0' } },
          'peer@3.0.0': {},
        },
        snapshots: {
          'consumer@1.0.0(peer@3.0.0)': { dependencies: { peer: '3.0.0' } },
          'consumer@2.0.0(peer@3.0.0)': { dependencies: { peer: '3.0.0' } },
          'peer@3.0.0': {},
        },
      },
    };
  }

  it('uses importer-specific specifiers and peer-qualified snapshots with explicit overrides', () => {
    const fixture = inputs();
    expect(findPnpmLockProblems(fixture)).toEqual([]);
    fixture.manifests['packages/widget'].dependencies.consumer = '^3.0.0';
    expect(findPnpmLockProblems(fixture)).toEqual([
      expect.objectContaining({
        workspace: 'packages/widget',
        field: 'dependencies.consumer.specifier',
        lockValue: '^2.0.0',
      }),
    ]);
  });

  it('rejects stale overrides, settings, patch bytes, and missing importers', () => {
    const fixture = inputs();
    const changed = {
      ...fixture,
      config: { overrides: {}, autoInstallPeers: false },
      patchHashes: { 'native@1.0.0': 'changed-content-hash' },
    };
    changed.lock.importers = {
      '.': changed.lock.importers['.'],
    } as typeof changed.lock.importers;
    const fields = findPnpmLockProblems(changed).map(
      (entry: { field: string }) => entry.field,
    );
    expect(fields).toEqual(
      expect.arrayContaining([
        'importers',
        'overrides',
        'settings.autoInstallPeers',
        'patchedDependencies',
      ]),
    );
  });

  it('checks package-extension configuration against the native pnpm checksum', () => {
    // Independently generated by pnpm 11.25.0 lockfile-only resolution.
    const packageExtensions = {
      '@kontourai/flow-agents@6.2.0': {
        dependencies: { '@kontourai/datum': '0.7.0' },
      },
    };
    const expected = 'sha256-8U/NwfVvJih09yZJqI4A31Zbu76ddMrtGmxoWvtwaaI=';
    expect(pnpmPackageExtensionsChecksum(packageExtensions)).toBe(expected);
    const fixture = inputs();
    const changed = {
      ...fixture,
      config: { ...fixture.config, packageExtensions },
      lock: { ...fixture.lock, packageExtensionsChecksum: expected },
    };
    expect(findPnpmLockProblems(changed)).toEqual([]);
    changed.config.packageExtensions[
      '@kontourai/flow-agents@6.2.0'
    ].dependencies['@kontourai/datum'] = '0.8.0';
    expect(findPnpmLockProblems(changed)).toEqual([
      expect.objectContaining({
        field: 'packageExtensionsChecksum',
        lockValue: expected,
      }),
    ]);
  });

  it('rejects an unresolved snapshot and unsatisfied or missing peers even with a frozen-installable lock', () => {
    const fixture = inputs();
    fixture.lock.snapshots['consumer@2.0.0(peer@3.0.0)'].dependencies.peer =
      '4.0.0';
    expect(findPnpmLockProblems(fixture)).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ field: 'peer.peer', lockValue: '4.0.0' }),
        expect.objectContaining({ field: 'peer.peer.snapshot' }),
      ]),
    );
    delete (
      fixture.lock.snapshots['consumer@2.0.0(peer@3.0.0)']
        .dependencies as Record<string, string>
    ).peer;
    expect(findPnpmLockProblems(fixture)).toEqual([
      expect.objectContaining({ field: 'peer.peer', lockValue: undefined }),
    ]);
    delete (fixture.lock.snapshots as Record<string, unknown>)[
      'consumer@2.0.0(peer@3.0.0)'
    ];
    expect(findPnpmLockProblems(fixture)).toEqual([
      expect.objectContaining({ field: 'dependencies.consumer.snapshot' }),
    ]);
  });
});
