// Generated by scripts/channel-ports.mjs from config/release-manifest-keys.json.
export const STATION_RELEASE_MANIFEST_KEYS = {
  keys: [
    {
      keyId: 'station-portable-nightly-2026-09',
      algorithm: 'ed25519',
      publicKeySpkiPem:
        '-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAH74uCwGmcJFftH+reVCJjJysQRRON2k0mTUoDBf14OM=\n-----END PUBLIC KEY-----\n',
      channels: ['nightly'],
    },
    {
      keyId: 'station-portable-release-2026-09',
      algorithm: 'ed25519',
      publicKeySpkiPem:
        '-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAk8YKOCVgKcXsNNMjkGwYOfE53pV1zrajakwI91oxbPo=\n-----END PUBLIC KEY-----\n',
      channels: ['stable', 'preview'],
    },
  ],
};
