import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const contract = JSON.parse(
  readFileSync(resolve(root, 'config/channel-ports.json'), 'utf8'),
);
export const CHANNEL_PORTS = contract.channels;

export function channelPorts(channel) {
  const ports = CHANNEL_PORTS[channel];
  if (!ports) throw new Error(`Unknown Station channel: ${channel}`);
  return ports;
}

function sharedTypeScript() {
  const lines = [
    '// Generated by scripts/channel-ports.mjs from config/channel-ports.json.',
    'export const STATION_CHANNEL_PORTS_DATA = {',
  ];
  for (const [channel, allocation] of Object.entries(CHANNEL_PORTS)) {
    lines.push(
      `  ${channel}: {`,
      `    uiPort: ${allocation.uiPort},`,
      `    serverPort: ${allocation.serverPort},`,
      `    consentPort: ${allocation.consentPort},`,
      `    instanceDirectory: '${allocation.instanceDirectory}',`,
      '  },',
    );
  }
  lines.push('} as const;', '');
  return lines.join('\n');
}

function rustSource() {
  const lines = [
    '// Generated by scripts/channel-ports.mjs from config/channel-ports.json.',
  ];
  lines.push(
    "pub fn desktop_channel_from_identifier(identifier: &str) -> Option<&'static str> {",
  );
  lines.push('    match identifier {');
  for (const channel of ['stable', 'beta', 'nightly']) {
    const identifier =
      channel === 'stable'
        ? 'io.kontourai.station'
        : `io.kontourai.station.${channel}`;
    lines.push(`        "${identifier}" => Some("${channel}"),`);
  }
  lines.push('        _ => None,');
  lines.push('    }');
  lines.push('}\n');
  lines.push(
    'pub fn default_desktop_port(channel: Option<&str>) -> Option<u16> {',
  );
  lines.push('    match channel {');
  for (const channel of ['stable', 'beta', 'nightly'])
    lines.push(
      `        Some("${channel}") => Some(${CHANNEL_PORTS[channel].serverPort.toLocaleString('en-US').replace(/,/g, '_')}),`,
    );
  lines.push('        _ => None,');
  lines.push('    }');
  lines.push('}\n');
  lines.push(
    'pub fn default_desktop_ui_port(channel: Option<&str>) -> Option<u16> {',
  );
  lines.push('    match channel {');
  for (const channel of ['stable', 'beta', 'nightly'])
    lines.push(
      `        Some("${channel}") => Some(${CHANNEL_PORTS[channel].uiPort.toLocaleString('en-US').replace(/,/g, '_')}),`,
    );
  lines.push('        _ => None,');
  lines.push('    }');
  lines.push('}\n');
  // station#3677: the consent listener's channel port. No desktop consumer
  // until the native approval broker (PR 3) lands, hence the allow attribute.
  lines.push('#[allow(dead_code)]');
  lines.push(
    'pub fn default_desktop_consent_port(channel: Option<&str>) -> Option<u16> {',
  );
  lines.push('    match channel {');
  for (const channel of ['stable', 'beta', 'nightly'])
    lines.push(
      `        Some("${channel}") => Some(${CHANNEL_PORTS[channel].consentPort.toLocaleString('en-US').replace(/,/g, '_')}),`,
    );
  lines.push('        _ => None,');
  lines.push('    }');
  lines.push('}\n');
  lines.push(
    "pub fn station_instance_directory(channel: Option<&str>) -> &'static str {",
  );
  lines.push('    match channel {');
  for (const channel of ['stable', 'beta', 'nightly'])
    lines.push(
      `        Some("${channel}") => "${CHANNEL_PORTS[channel].instanceDirectory}",`,
    );
  lines.push(`        _ => "${CHANNEL_PORTS.development.instanceDirectory}",`);
  lines.push('    }');
  lines.push('}\n');
  return lines.join('\n');
}

function plist(channel) {
  const ports = CHANNEL_PORTS[channel];
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0"><dict><key>CFBundleIdentifier</key><string>${channel === 'stable' ? 'io.kontourai.station' : `io.kontourai.station.${channel}`}</string><key>StationChannel</key><string>${channel}</string><key>StationServerPort</key><integer>${ports.serverPort}</integer><key>LSEnvironment</key><dict><key>STATION_DESKTOP_CHANNEL</key><string>${channel}</string><key>STATION_DESKTOP_PORT</key><string>${ports.serverPort}</string></dict></dict></plist>\n`;
}

export function syncGeneratedChannelPorts() {
  writeFileSync(
    resolve(root, 'packages/shared/src/channel-ports.generated.ts'),
    sharedTypeScript(),
  );
  writeFileSync(
    resolve(root, 'src-desktop/src/channel_ports_generated.rs'),
    rustSource(),
  );
  for (const channel of ['stable', 'beta', 'nightly'])
    writeFileSync(
      resolve(root, 'src-desktop', `Info.${channel}.plist`),
      plist(channel),
    );
}

export function checkGeneratedChannelPorts() {
  const expected = new Map([
    [
      resolve(root, 'packages/shared/src/channel-ports.generated.ts'),
      sharedTypeScript(),
    ],
    [resolve(root, 'src-desktop/src/channel_ports_generated.rs'), rustSource()],
    ...['stable', 'beta', 'nightly'].map((channel) => [
      resolve(root, 'src-desktop', `Info.${channel}.plist`),
      plist(channel),
    ]),
  ]);
  for (const [path, contents] of expected) {
    let actual = '';
    try {
      actual = readFileSync(path, 'utf8');
    } catch {}
    if (actual !== contents)
      throw new Error(`Generated channel-port file is stale: ${path}`);
  }
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  if (process.argv[2] === '--sync-desktop') syncGeneratedChannelPorts();
  else if (process.argv[2] === '--check') checkGeneratedChannelPorts();
  else
    process.stdout.write(`${JSON.stringify(channelPorts(process.argv[2]))}\n`);
}
