import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { invokedDirectly } from './lib/module-entry.mjs';

const root = resolve(import.meta.dirname, '..');
const contract = JSON.parse(
  readFileSync(resolve(root, 'config/channel-ports.json'), 'utf8'),
);
export const CHANNEL_PORTS = contract.channels;

/**
 * The installable release rings (#2675): each names the runtime channel it
 * installs as, whether it is a prerelease, and its owned launcher. A
 * prerelease ring's tags are `vX.Y.Z-<ring>.N`; the one non-prerelease ring
 * owns the unlabelled `vX.Y.Z`. Validated here so every generated consumer
 * (shared TypeScript, install.sh) rejects a malformed table the same way.
 */
export const RELEASE_RINGS = validateReleaseRings(contract.releaseRings);

function validateReleaseRings(rings) {
  if (!rings || typeof rings !== 'object' || Array.isArray(rings))
    throw new Error('config/channel-ports.json releaseRings must be an object');
  const runtimes = new Set();
  let unlabelled = 0;
  for (const [ring, entry] of Object.entries(rings)) {
    const keys = Object.keys(entry ?? {}).sort();
    if (
      !/^[a-z]+$/.test(ring) ||
      JSON.stringify(keys) !==
        JSON.stringify(['launcher', 'prerelease', 'runtimeChannel']) ||
      typeof entry.prerelease !== 'boolean' ||
      !/^station(-[a-z]+)?$/.test(entry.launcher) ||
      entry.runtimeChannel === 'development' ||
      !Object.hasOwn(CHANNEL_PORTS, entry.runtimeChannel) ||
      runtimes.has(entry.runtimeChannel)
    )
      throw new Error(
        `Invalid release ring in config/channel-ports.json: ${ring}`,
      );
    runtimes.add(entry.runtimeChannel);
    if (!entry.prerelease) unlabelled += 1;
  }
  if (unlabelled !== 1)
    throw new Error(
      'config/channel-ports.json releaseRings must have exactly one non-prerelease ring',
    );
  return rings;
}

export function channelPorts(channel) {
  const ports = CHANNEL_PORTS[channel];
  if (!ports) throw new Error(`Unknown Station channel: ${channel}`);
  return ports;
}

function sharedTypeScript() {
  const lines = [
    '// Generated by scripts/channel-ports.mjs from config/channel-ports.json.',
    'export const STATION_CHANNEL_PORTS_DATA = {',
  ];
  for (const [channel, allocation] of Object.entries(CHANNEL_PORTS)) {
    lines.push(
      `  ${channel}: {`,
      `    uiPort: ${allocation.uiPort},`,
      `    serverPort: ${allocation.serverPort},`,
      `    consentPort: ${allocation.consentPort},`,
      `    instanceDirectory: '${allocation.instanceDirectory}',`,
      '  },',
    );
  }
  lines.push('} as const;', '');
  lines.push('export const STATION_RELEASE_RINGS_DATA = {');
  for (const [ring, entry] of Object.entries(RELEASE_RINGS)) {
    lines.push(
      `  ${ring}: {`,
      `    runtimeChannel: '${entry.runtimeChannel}',`,
      `    prerelease: ${entry.prerelease},`,
      `    launcher: '${entry.launcher}',`,
      '  },',
    );
  }
  lines.push('} as const;', '');
  return lines.join('\n');
}

// The shared release-manifest verifier is plain JavaScript (the installer's
// verifier and the signer load it without a TypeScript step), so it reads the
// ring table from this projection rather than the generated TypeScript.
function sharedReleaseRingsModule() {
  const lines = [
    '// Generated by scripts/channel-ports.mjs from config/channel-ports.json.',
    'export const STATION_RELEASE_RINGS = Object.freeze({',
  ];
  for (const [ring, entry] of Object.entries(RELEASE_RINGS))
    lines.push(
      `  ${ring}: Object.freeze({`,
      `    runtimeChannel: '${entry.runtimeChannel}',`,
      `    prerelease: ${entry.prerelease},`,
      `    launcher: '${entry.launcher}',`,
      '  }),',
    );
  lines.push('});', '');
  return lines.join('\n');
}

// The pinned release-manifest signing keys (public halves), projected into the
// shared package so a consumer bundled from it (the Windows installer core)
// carries them without reaching outside the package it is published from.
const MANIFEST_KEYS = JSON.parse(
  readFileSync(resolve(root, 'config/release-manifest-keys.json'), 'utf8'),
);
function sharedReleaseManifestKeys() {
  const lines = [
    '// Generated by scripts/channel-ports.mjs from config/release-manifest-keys.json.',
    'export const STATION_RELEASE_MANIFEST_KEYS = {',
    '  keys: [',
  ];
  // Single-quoted, as the formatter prints TypeScript; none of these values
  // contains a quote, and JSON escaping keeps the PEM's newlines as \n.
  const quoted = (value) => `'${JSON.stringify(value).slice(1, -1)}'`;
  for (const key of MANIFEST_KEYS.keys)
    lines.push(
      '    {',
      `      keyId: ${quoted(key.keyId)},`,
      `      algorithm: ${quoted(key.algorithm)},`,
      '      publicKeySpkiPem:',
      `        ${quoted(key.publicKeySpkiPem)},`,
      `      channels: [${key.channels.map(quoted).join(', ')}],`,
      '    },',
    );
  lines.push('  ],', '};', '');
  return lines.join('\n');
}

function rustSource() {
  const lines = [
    '// Generated by scripts/channel-ports.mjs from config/channel-ports.json.',
  ];
  lines.push(
    "pub fn desktop_channel_from_identifier(identifier: &str) -> Option<&'static str> {",
  );
  lines.push('    match identifier {');
  for (const channel of ['stable', 'beta', 'nightly']) {
    const identifier =
      channel === 'stable'
        ? 'io.kontourai.station'
        : `io.kontourai.station.${channel}`;
    lines.push(`        "${identifier}" => Some("${channel}"),`);
  }
  lines.push('        _ => None,');
  lines.push('    }');
  lines.push('}\n');
  lines.push(
    'pub fn default_desktop_port(channel: Option<&str>) -> Option<u16> {',
  );
  lines.push('    match channel {');
  for (const channel of ['stable', 'beta', 'nightly'])
    lines.push(
      `        Some("${channel}") => Some(${CHANNEL_PORTS[channel].serverPort.toLocaleString('en-US').replace(/,/g, '_')}),`,
    );
  lines.push('        _ => None,');
  lines.push('    }');
  lines.push('}\n');
  lines.push(
    'pub fn default_desktop_ui_port(channel: Option<&str>) -> Option<u16> {',
  );
  lines.push('    match channel {');
  for (const channel of ['stable', 'beta', 'nightly'])
    lines.push(
      `        Some("${channel}") => Some(${CHANNEL_PORTS[channel].uiPort.toLocaleString('en-US').replace(/,/g, '_')}),`,
    );
  lines.push('        _ => None,');
  lines.push('    }');
  lines.push('}\n');
  // station#3677: the consent listener's channel port. No desktop consumer
  // until the native approval broker (PR 3) lands, hence the allow attribute.
  lines.push('#[allow(dead_code)]');
  lines.push(
    'pub fn default_desktop_consent_port(channel: Option<&str>) -> Option<u16> {',
  );
  lines.push('    match channel {');
  for (const channel of ['stable', 'beta', 'nightly'])
    lines.push(
      `        Some("${channel}") => Some(${CHANNEL_PORTS[channel].consentPort.toLocaleString('en-US').replace(/,/g, '_')}),`,
    );
  lines.push('        _ => None,');
  lines.push('    }');
  lines.push('}\n');
  lines.push(
    "pub fn station_instance_directory(channel: Option<&str>) -> &'static str {",
  );
  lines.push('    match channel {');
  for (const channel of ['stable', 'beta', 'nightly'])
    lines.push(
      `        Some("${channel}") => "${CHANNEL_PORTS[channel].instanceDirectory}",`,
    );
  lines.push(`        _ => "${CHANNEL_PORTS.development.instanceDirectory}",`);
  lines.push('    }');
  lines.push('}\n');
  return lines.join('\n');
}

function plist(channel) {
  const ports = CHANNEL_PORTS[channel];
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0"><dict><key>CFBundleIdentifier</key><string>${channel === 'stable' ? 'io.kontourai.station' : `io.kontourai.station.${channel}`}</string><key>NSCameraUsageDescription</key><string>Station uses the camera to scan pairing codes from another device.</string><key>NSMicrophoneUsageDescription</key><string>Station uses the microphone for voice conversations with your agents.</string><key>NSLocalNetworkUsageDescription</key><string>Station connects to Station hosts on your local network.</string><key>StationChannel</key><string>${channel}</string><key>StationServerPort</key><integer>${ports.serverPort}</integer><key>LSEnvironment</key><dict><key>STATION_DESKTOP_CHANNEL</key><string>${channel}</string><key>STATION_DESKTOP_PORT</key><string>${ports.serverPort}</string></dict></dict></plist>\n`;
}

function generatedFiles(outputRoot) {
  return new Map([
    [
      resolve(outputRoot, 'packages/shared/src/channel-ports.generated.ts'),
      sharedTypeScript(),
    ],
    [
      resolve(outputRoot, 'packages/shared/src/release-rings.generated.mjs'),
      sharedReleaseRingsModule(),
    ],
    [
      resolve(
        outputRoot,
        'packages/shared/src/release-manifest-keys.generated.ts',
      ),
      sharedReleaseManifestKeys(),
    ],
    [
      resolve(outputRoot, 'src-desktop/src/channel_ports_generated.rs'),
      rustSource(),
    ],
    ...['stable', 'beta', 'nightly'].map((channel) => [
      resolve(outputRoot, 'src-desktop', `Info.${channel}.plist`),
      plist(channel),
    ]),
  ]);
}

// `outputRoot` lets a caller check or regenerate a copy of the tree; the
// contract itself is always read from this checkout's config.
export function syncGeneratedChannelPorts({ outputRoot = root } = {}) {
  for (const [path, contents] of generatedFiles(outputRoot))
    writeFileSync(path, contents);
}

export function checkGeneratedChannelPorts({ outputRoot = root } = {}) {
  for (const [path, contents] of generatedFiles(outputRoot)) {
    let actual = '';
    try {
      actual = readFileSync(path, 'utf8');
    } catch {}
    if (actual !== contents)
      throw new Error(`Generated channel-port file is stale: ${path}`);
  }
}

if (invokedDirectly(import.meta.url)) {
  if (process.argv[2] === '--sync-desktop') syncGeneratedChannelPorts();
  else if (process.argv[2] === '--check') checkGeneratedChannelPorts();
  else
    process.stdout.write(`${JSON.stringify(channelPorts(process.argv[2]))}\n`);
}
