#!/usr/bin/env node
// Generates the file index inside docs/design/README.md and
// docs/plans/README.md between the docs-index markers, one line per tracked
// markdown file with its own H1 as the description. `--check` regenerates and
// diffs instead of writing (the docs:issue-lifecycle:check pattern), so the
// indexes cannot silently omit a record again — docs/design/README.md linked
// 2 of 44 files when this was introduced, and docs/plans/README.md 5 of 8.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');

export const INDEXED_DIRECTORIES = Object.freeze(['docs/design', 'docs/plans']);

const START =
  '<!-- docs-index:start (generated by scripts/docs-index.mjs; run `npm run docs:index`) -->';
const END = '<!-- docs-index:end -->';

function trackedMarkdown(directory) {
  return execFileSync('git', ['ls-files', '--', `${directory}/*.md`], {
    cwd: repoRoot,
    encoding: 'utf8',
    windowsHide: true,
  })
    .split('\n')
    .filter(Boolean)
    .filter((path) => basename(path) !== 'README.md')
    .sort();
}

function titleOf(path) {
  const body = readFileSync(resolve(repoRoot, path), 'utf8');
  const heading = body.split('\n').find((line) => line.startsWith('# '));
  return heading ? heading.slice(2).trim() : basename(path, '.md');
}

export function renderIndex(directory) {
  const readmeDir = directory;
  const lines = trackedMarkdown(directory).map((path) => {
    const rel = relative(readmeDir, path);
    return `- [${rel}](${rel}) — ${titleOf(path)}`;
  });
  return [START, ...lines, END].join('\n');
}

export function applyIndex(readmeBody, rendered) {
  const startAt = readmeBody.indexOf(START);
  const endAt = readmeBody.indexOf(END);
  if (startAt === -1 || endAt === -1) {
    throw new Error(
      'docs-index markers are missing; restore the docs-index:start/end block',
    );
  }
  return (
    readmeBody.slice(0, startAt) +
    rendered +
    readmeBody.slice(endAt + END.length)
  );
}

export function main(argv = process.argv.slice(2)) {
  const check = argv.includes('--check');
  let drifted = 0;
  for (const directory of INDEXED_DIRECTORIES) {
    const readmePath = resolve(repoRoot, directory, 'README.md');
    const current = readFileSync(readmePath, 'utf8');
    const next = applyIndex(current, renderIndex(directory));
    if (next === current) continue;
    if (check) {
      drifted += 1;
      console.error(
        `docs-index: ${directory}/README.md does not match its tracked files; run \`npm run docs:index\``,
      );
    } else {
      writeFileSync(readmePath, next);
      console.log(`docs-index: regenerated ${directory}/README.md`);
    }
  }
  if (check && drifted > 0) process.exit(1);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
