/**
 * Generates `src-server/generated/settings-registry.json` — the agent-facing
 * enumeration of every settings control and the deep link that opens it
 * (#2144 slice 5). `GET /api/settings/registry` serves this file verbatim.
 *
 * ## Generated and checked in, not extracted at request time
 *
 * The owner decision on #2144 was explicit: no extraction-based generation
 * at runtime. The artifact is built here, committed, and held to the sources
 * by `settings:registry:gate` (this script with `--check`) inside
 * `verify:static:raw` — the same shape as
 * `scripts/agent-plugin-validators-gate.mjs`. A route that derived the list
 * on each request would make the UI catalog a server dependency and put a
 * `src-ui` import inside the server bundle.
 *
 * ## Why the catalog is loaded through a computed specifier
 *
 * `scripts/**` is typechecked as its own project (`tsconfig.scripts.json`,
 * held exhaustive by `npm run typecheck:scripts`). That project has no `jsx`
 * setting and no `vite/client` types, and `settings-catalog.ts` transitively
 * reaches a `.tsx` module and `import.meta.env` — a static import of it puts
 * three unfixable errors into the scripts program. A computed specifier is
 * not followed by `tsc`, so this file stays fully typechecked while the UI
 * module stays out of the scripts program; `tsx` resolves it at run time.
 *
 * What that costs is compile-time coupling to the catalog's own types, so
 * the shape is validated here at run time instead (`loadRegistrySources`), and
 * every emitted entry is asserted by
 * `scripts/__tests__/gen-settings-registry.test.ts`.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

/** The checked-in artifact, repository-relative. */
export const REGISTRY_ARTIFACT_PATH =
  'src-server/generated/settings-registry.json';
const OUTPUT_PATH = join(ROOT, REGISTRY_ARTIFACT_PATH);

/**
 * Every module the artifact is built from, repository-relative, in the order
 * `loadRegistrySources` destructures them.
 *
 * Exported because the computed specifier below is invisible to the import
 * graph: a change to any of these never reaches
 * `scripts/__tests__/gen-settings-registry.test.ts` through `vitest related`,
 * so the pull-request lane only schedules that suite through the impact
 * manifest's edges for these paths (#2176). The suite asserts each one is
 * still selected, so adding a source here without an edge reds it.
 */
export const REGISTRY_SOURCE_PATHS = Object.freeze([
  'src-ui/src/views/settings/settings-catalog.ts',
  'src-ui/src/views/settings/settings-deep-link.ts',
  'packages/contracts/src/settings-registry.ts',
  'packages/contracts/src/device-settings.ts',
] as const);

/**
 * A floor, not a pin. The catalog stood at 45 entries when this landed; a
 * run that produced materially fewer means a source failed to load or an
 * enumeration silently shrank, and writing that file would quietly delete
 * deep links agents were told about. Pinning the exact count instead would
 * red on every ordinary settings addition.
 */
export const MINIMUM_REGISTRY_ENTRIES = 40;

/**
 * The second floor, for the degraded case the first one cannot see: 32 of
 * the 45 entries carry a `configKey`, and `configKey` is what resolves the
 * `help` sentence. A rename on the registry side — or a registry that loaded
 * but produced no usable definitions — leaves the entry COUNT untouched
 * while every entry silently loses its key and its help. The artifact would
 * still be 45 rows of labels and routes, above the first floor, and agents
 * would answer with links and no consequence sentence.
 */
export const MINIMUM_REGISTRY_CONFIG_KEYS = 20;

export const REGISTRY_COMMENT =
  'Generated by scripts/gen-settings-registry.ts from the settings catalog and the settings registries; do not edit. Run `npm run gen:settings-registry` after changing either.';

export interface SettingsRegistryEntry {
  id: string;
  label: string;
  help?: string;
  scope: string;
  section: string;
  route: string;
  configKey?: string;
}

export interface SettingsRegistryDocument {
  $comment: string;
  settings: SettingsRegistryEntry[];
}

/** The subset of the UI catalog entry this artifact is built from. */
interface CatalogEntry {
  id: string;
  title: string;
  section: string;
  scope: string;
  configKeys?: readonly string[];
  /**
   * An entry with no config key has no registry definition to take a help
   * sentence from, so the catalog may carry one directly. Nothing declares
   * one today; those entries are emitted without `help` rather than with a
   * fabricated one.
   */
  help?: string;
}

interface SettingDefinition {
  key: string;
  help: string;
}

function assertNonEmptyString(value: unknown, what: string): string {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new Error(`${what} is not a non-empty string`);
  }
  return value;
}

export async function loadRegistrySources(root = ROOT) {
  const load = (relative: string) =>
    import(pathToFileURL(join(root, relative)).href) as Promise<
      Record<string, unknown>
    >;
  const [catalogModule, deepLinkModule, appRegistry, deviceRegistry] =
    await Promise.all(REGISTRY_SOURCE_PATHS.map(load));

  const catalog = catalogModule.SETTINGS_CATALOG;
  if (!Array.isArray(catalog)) {
    throw new Error('SETTINGS_CATALOG did not load as an array');
  }
  const settingsDeepLinkUrl = deepLinkModule.settingsDeepLinkUrl;
  if (typeof settingsDeepLinkUrl !== 'function') {
    throw new Error('settingsDeepLinkUrl did not load as a function');
  }

  const definitions = new Map<string, SettingDefinition>();
  for (const registry of [
    appRegistry.APP_SETTINGS_REGISTRY,
    deviceRegistry.DEVICE_SETTINGS_REGISTRY,
  ]) {
    if (!Array.isArray(registry)) {
      throw new Error('a settings registry did not load as an array');
    }
    for (const definition of registry as SettingDefinition[]) {
      definitions.set(String(definition.key), definition);
    }
  }

  return {
    catalog: catalog as CatalogEntry[],
    definitions,
    buildRoute: settingsDeepLinkUrl as (target: {
      view: string;
      highlight: string;
    }) => string,
  };
}

export function buildRegistryDocument(sources: {
  catalog: readonly CatalogEntry[];
  definitions: ReadonlyMap<string, SettingDefinition>;
  buildRoute: (target: { view: string; highlight: string }) => string;
}): SettingsRegistryDocument {
  const settings = sources.catalog.map((entry): SettingsRegistryEntry => {
    const configKey = entry.configKeys?.[0];
    // The FIRST config key, deliberately: a catalog entry with several keys
    // is one control over one primary value, and the registry names the
    // control. Callers that need the whole set read `GET /config/app`.
    const help = configKey
      ? sources.definitions.get(configKey)?.help
      : entry.help;
    return {
      id: assertNonEmptyString(entry.id, 'catalog id'),
      label: assertNonEmptyString(entry.title, `${entry.id} title`),
      ...(help !== undefined && help !== ''
        ? { help: assertNonEmptyString(help, `${entry.id} help`) }
        : {}),
      scope: assertNonEmptyString(entry.scope, `${entry.id} scope`),
      section: assertNonEmptyString(entry.section, `${entry.id} section`),
      route: sources.buildRoute({ view: entry.section, highlight: entry.id }),
      ...(configKey ? { configKey } : {}),
    };
  });
  return { $comment: REGISTRY_COMMENT, settings };
}

export function serializeRegistry(document: SettingsRegistryDocument): string {
  return `${JSON.stringify(document, null, 2)}\n`;
}

export async function generateSettingsRegistry({
  check = false,
  root = ROOT,
  outputPath = OUTPUT_PATH,
  sources,
}: {
  check?: boolean;
  root?: string;
  outputPath?: string;
  /**
   * Injected only by the tests, so the floor below can be driven with a
   * catalog one entry short. A guardrail whose rejection branch never
   * executes is unproven, and the real catalog cannot be made small.
   */
  sources?: Awaited<ReturnType<typeof loadRegistrySources>>;
} = {}) {
  const document = buildRegistryDocument(
    sources ?? (await loadRegistrySources(root)),
  );
  if (document.settings.length < MINIMUM_REGISTRY_ENTRIES) {
    throw new Error(
      `Refusing to write ${outputPath}: ${document.settings.length} settings is below the floor of ${MINIMUM_REGISTRY_ENTRIES}. A source failed to load or the catalog shrank; check before lowering this.`,
    );
  }
  const withConfigKey = document.settings.filter(
    (entry) => entry.configKey !== undefined,
  ).length;
  if (withConfigKey < MINIMUM_REGISTRY_CONFIG_KEYS) {
    throw new Error(
      `Refusing to write ${outputPath}: only ${withConfigKey} of ${document.settings.length} settings carry a config key, below the floor of ${MINIMUM_REGISTRY_CONFIG_KEYS}. A registry key was renamed or a registry failed to load; the entry count alone would not have shown this.`,
    );
  }
  const serialized = serializeRegistry(document);
  if (check) {
    let current: string;
    try {
      current = readFileSync(outputPath, 'utf8');
    } catch {
      throw new Error(
        `${outputPath} is missing. Run \`npm run gen:settings-registry\`.`,
      );
    }
    if (current !== serialized) {
      throw new Error(
        `${outputPath} is stale — it does not match the settings catalog and registries. Run \`npm run gen:settings-registry\` and commit the result.`,
      );
    }
    return { written: false, entries: document.settings.length };
  }
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, serialized, 'utf8');
  return { written: true, entries: document.settings.length };
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const check = process.argv.includes('--check');
  try {
    const result = await generateSettingsRegistry({ check });
    console.log(
      check
        ? `settings registry is current (${result.entries} settings)`
        : `Generated ${OUTPUT_PATH} (${result.entries} settings)`,
    );
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
